/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.semantic

import androidx.compose.ui.unit.dp
import com.instructure.instui.primitives.InstUISizes

/**
 * InstUI Layout Sizes.
 *
 * Semantic sizing values for interactive elements, spacing, borders, etc.
 */
object InstUILayoutSizes {
    object BorderRadius {
        object Container {
            val sm = InstUISizes.size8
            val md = InstUISizes.size16
            val lg = InstUISizes.size24
            val xl = InstUISizes.size32
        }
        object Full {
            val full = 15984.dp
        }
        object Interactive {
            val base = InstUISizes.size12
        }
        object Lg {
            val lg = InstUISizes.size12
        }
        object Md {
            val md = InstUISizes.size8
        }
        object Sm {
            val sm = InstUISizes.size4
        }
        object Xl {
            val xl = InstUISizes.size16
        }
        object Xs {
            val xs = InstUISizes.size2
        }
        object Xxl {
            val xxl = InstUISizes.size24
        }
    }

    object BorderWidth {
        object Interactive {
            val base = InstUISizes.size1
            val focus = InstUISizes.size2
        }
        object Lg {
            val lg = InstUISizes.size4
        }
        object Md {
            val md = InstUISizes.size2
        }
        object Sm {
            val sm = InstUISizes.size1
        }
    }

    object Size {
        object Breakpoints {
            val xxs = 128.dp
            val xs = 256.dp
            val sm = 480.dp
            val md = 768.dp
            val lg = 992.dp
            val desktop = 1024.dp
            val xl = 1200.dp
        }
        object ChoiceControl {
            val height_sm = InstUISizes.size24
            val height_md = InstUISizes.size24
            val height_lg = InstUISizes.size24
        }
        object Interactive {
            val height_xxs = InstUISizes.size20
            val height_xs = InstUISizes.size24
            val height_sm = InstUISizes.size32
            val height_md = InstUISizes.size40
            val height_lg = InstUISizes.size48
        }
        object Media {
            val mediumMin = 768.dp
            val largeMin = 992.dp
            val xLargeMin = 1200.dp
        }
    }

    object Spacing {
        object Gap {
            val sections = InstUISizes.size48
            val cards_sm = InstUISizes.size16
            val cards_md = InstUISizes.size24
            val cards_lg = InstUISizes.size32
            val inputs_horizontal = InstUISizes.size12
            val inputs_vertical = InstUISizes.size16
            val inputElements = InstUISizes.size8
        }
        object Padding {
            val container_xxs = InstUISizes.size8
            val container_xs = InstUISizes.size12
            val container_sm = InstUISizes.size16
            val container_md = InstUISizes.size24
            val container_lg = InstUISizes.size32
            val interactive_horizontal_sm = InstUISizes.size8
            val interactive_horizontal_md = InstUISizes.size12
            val interactive_horizontal_lg = InstUISizes.size16
            val interactive_horizontal_xl = InstUISizes.size20
        }
        object Space2xl {
            val space2xl = InstUISizes.size32
        }
        object Space2xs {
            val space2xs = InstUISizes.size2
        }
        object SpaceLg {
            val spaceLg = InstUISizes.size16
        }
        object SpaceMd {
            val spaceMd = InstUISizes.size12
        }
        object SpaceSm {
            val spaceSm = InstUISizes.size8
        }
        object SpaceXl {
            val spaceXl = InstUISizes.size24
        }
        object SpaceXs {
            val spaceXs = InstUISizes.size4
        }
    }
}
