/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.Apps: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.Apps",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M6.2 3H3.8C3.35817 3 3 3.35817 3 3.8V6.2C3 6.64183 3.35817 7 3.8 7H6.2C6.64183 7 7 6.64183 7 6.2V3.8C7 3.35817 6.64183 3 6.2 3Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M6.2 10H3.8C3.35817 10 3 10.3582 3 10.8V13.2C3 13.6418 3.35817 14 3.8 14H6.2C6.64183 14 7 13.6418 7 13.2V10.8C7 10.3582 6.64183 10 6.2 10Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M6.2 17H3.8C3.35817 17 3 17.3582 3 17.8V20.2C3 20.6418 3.35817 21 3.8 21H6.2C6.64183 21 7 20.6418 7 20.2V17.8C7 17.3582 6.64183 17 6.2 17Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M13.2 3H10.8C10.3582 3 10 3.35817 10 3.8V6.2C10 6.64183 10.3582 7 10.8 7H13.2C13.6418 7 14 6.64183 14 6.2V3.8C14 3.35817 13.6418 3 13.2 3Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M13.2 10H10.8C10.3582 10 10 10.3582 10 10.8V13.2C10 13.6418 10.3582 14 10.8 14H13.2C13.6418 14 14 13.6418 14 13.2V10.8C14 10.3582 13.6418 10 13.2 10Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M13.2 17H10.8C10.3582 17 10 17.3582 10 17.8V20.2C10 20.6418 10.3582 21 10.8 21H13.2C13.6418 21 14 20.6418 14 20.2V17.8C14 17.3582 13.6418 17 13.2 17Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M20.2 3H17.8C17.3582 3 17 3.35817 17 3.8V6.2C17 6.64183 17.3582 7 17.8 7H20.2C20.6418 7 21 6.64183 21 6.2V3.8C21 3.35817 20.6418 3 20.2 3Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M20.2 10H17.8C17.3582 10 17 10.3582 17 10.8V13.2C17 13.6418 17.3582 14 17.8 14H20.2C20.6418 14 21 13.6418 21 13.2V10.8C21 10.3582 20.6418 10 20.2 10Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M20.2 17H17.8C17.3582 17 17 17.3582 17 17.8V20.2C17 20.6418 17.3582 21 17.8 21H20.2C20.6418 21 21 20.6418 21 20.2V17.8C21 17.3582 20.6418 17 20.2 17Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
