/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.ClosedCaptionCheck: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.ClosedCaptionCheck",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M10.0001 9.17C9.54769 9.01087 9.06376 8.96249 8.58885 9.02894C8.11393 9.09538 7.66186 9.2747 7.27054 9.55188C6.87921 9.82905 6.56003 10.196 6.33975 10.6219C6.11947 11.0479 6.00452 11.5205 6.00452 12C6.00452 12.4795 6.11947 12.9521 6.33975 13.3781C6.56003 13.804 6.87921 14.171 7.27054 14.4481C7.66186 14.7253 8.11393 14.9046 8.58885 14.9711C9.06376 15.0375 9.54769 14.9891 10.0001 14.83M13.3398 10.6219C13.1195 11.0479 13.0045 11.5205 13.0045 12C13.0045 12.4795 13.1195 12.9521 13.3398 13.3781C13.56 13.804 13.8792 14.171 14.2705 14.4481C14.6619 14.7253 15.1139 14.9046 15.5888 14.9711C16.0638 15.0375 16.5477 14.9891 17.0001 14.83M12.5888 5H4C2.89543 5 2 5.89543 2 7V17C2 18.1046 2.89543 19 4 19H20C21.1046 19 22 18.1046 22 17V11"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M16 7L18 9L22 5"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
