/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.CopyrightPublicDomain: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.CopyrightPublicDomain",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M6.3226 15.0598V8.94019H8.77044C9.25735 8.94019 9.72432 9.13361 10.0686 9.4779C10.4129 9.8222 10.6063 10.2892 10.6063 10.7761C10.6063 11.263 10.4129 11.7299 10.0686 12.0742C9.72432 12.4185 9.25735 12.612 8.77044 12.612H6.3226M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12ZM13.6035 15.0598V8.94019H16.0513C16.5382 8.94019 17.0052 9.13361 17.3495 9.47791C17.6938 9.8222 17.8234 10.1853 17.8872 10.7761C17.9427 11.2892 18.0099 12.3912 17.8872 13.37C17.7991 14.0724 17.4933 14.5047 17.3495 14.6486C17.0052 14.9929 16.5382 15.0598 16.0513 15.0598H13.6035Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
