/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.ListSquare: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.ListSquare",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M11 6H21M11 12H21M11 18H21"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M6.33333 6H3.66667C3.29848 6 3 6.29848 3 6.66667V9.33333C3 9.70152 3.29848 10 3.66667 10H6.33333C6.70152 10 7 9.70152 7 9.33333V6.66667C7 6.29848 6.70152 6 6.33333 6Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M6.33333 14H3.66667C3.29848 14 3 14.2985 3 14.6667V17.3333C3 17.7015 3.29848 18 3.66667 18H6.33333C6.70152 18 7 17.7015 7 17.3333V14.6667C7 14.2985 6.70152 14 6.33333 14Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
