/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.MediaAttachment: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.MediaAttachment",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M18.3049 5.53399C13.4727 4.73346 8.54167 4.73346 3.70945 5.53399C3.40782 5.61669 3.13291 5.77647 2.91175 5.99763C2.69059 6.21879 2.53081 6.4937 2.44811 6.79533C1.81873 9.76553 1.81873 12.8347 2.44811 15.8049C2.53081 16.1065 2.69059 16.3814 2.91175 16.6026C3.13291 16.8237 3.40782 16.9835 3.70945 17.0662C5.42723 17.3508 7.1575 17.5343 8.89139 17.6166M17.8031 18.5733C17.8031 19.8987 16.7286 20.9731 15.4033 20.9731C14.0779 20.9731 13.0035 19.8987 13.0035 18.5733C13.0035 17.248 14.0779 16.1735 15.4033 16.1735C16.7286 16.1735 17.8031 17.248 17.8031 18.5733ZM17.8031 18.5733V8.97412L22.0027 11.3739M9.20526 14.003L13.71 11.3001L9.20526 8.59724V14.003Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun MediaAttachmentPreview() {
    Icon(
        imageVector = InstUIIcons.Custom.MediaAttachment,
        contentDescription = "MediaAttachment",
        modifier = Modifier.size(48.dp),
    )
}
