/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.SearchAi: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.SearchAi",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M21 20.9999L16.6569 16.6568M16.6569 16.6568L16.65 16.6499M16.6569 16.6568C17.2475 16.0662 17.7461 15.3838 18.1295 14.6327M16.6569 16.6568C15.2092 18.1045 13.2092 19 11 19C6.58172 19 3 15.4183 3 11C3 6.58172 6.58172 3 11 3C11.4734 3 11.9371 3.04111 12.3879 3.11996M17 3V11M17 3L18.0342 6.03742M17 3L15.9211 6.03742M17 11L15.9211 7.93588M17 11L18.0342 7.93588M21 7L18.0342 7.93588M21 7L18.0342 6.03742M21 7H13M13 7L15.9211 7.93588M13 7L15.9211 6.03742M15.9211 7.93588H18.0342M15.9211 7.93588V6.03742M18.0342 7.93588V6.03742M18.0342 6.03742H15.9211"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
