/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.StarSolid: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.StarSolid",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M11.5251 2.295C11.5689 2.20646 11.6366 2.13193 11.7205 2.07983C11.8045 2.02772 11.9013 2.00011 12.0001 2.00011C12.0989 2.00011 12.1957 2.02772 12.2796 2.07983C12.3636 2.13193 12.4313 2.20646 12.4751 2.295L14.7851 6.974C14.9373 7.28197 15.1619 7.54841 15.4397 7.75045C15.7175 7.9525 16.0402 8.08411 16.3801 8.134L21.5461 8.89C21.644 8.90418 21.7359 8.94547 21.8116 9.0092C21.8872 9.07293 21.9435 9.15655 21.9741 9.25061C22.0047 9.34467 22.0084 9.44541 21.9847 9.54144C21.961 9.63747 21.9109 9.72495 21.8401 9.794L18.1041 13.432C17.8577 13.6721 17.6734 13.9685 17.5669 14.2956C17.4605 14.6228 17.4352 14.9709 17.4931 15.31L18.3751 20.45C18.3924 20.5478 18.3818 20.6486 18.3446 20.7407C18.3074 20.8328 18.245 20.9126 18.1646 20.971C18.0842 21.0294 17.9891 21.064 17.89 21.0709C17.7908 21.0778 17.6918 21.0567 17.6041 21.01L12.9861 18.582C12.6818 18.4222 12.3433 18.3388 11.9996 18.3388C11.6559 18.3388 11.3174 18.4222 11.0131 18.582L6.39609 21.01C6.30842 21.0564 6.20949 21.0773 6.11054 21.0703C6.0116 21.0632 5.91661 21.0286 5.83639 20.9702C5.75616 20.9119 5.69392 20.8322 5.65675 20.7402C5.61957 20.6483 5.60895 20.5477 5.62609 20.45L6.50709 15.311C6.56529 14.9717 6.54007 14.6234 6.43363 14.296C6.32718 13.9687 6.1427 13.6722 5.89609 13.432L2.16009 9.795C2.08868 9.72603 2.03808 9.6384 2.01405 9.54207C1.99002 9.44575 1.99353 9.34462 2.02417 9.25019C2.05481 9.15576 2.11136 9.07184 2.18737 9.00798C2.26338 8.94413 2.35579 8.9029 2.45409 8.889L7.61909 8.134C7.95935 8.0845 8.28248 7.95306 8.56067 7.75099C8.83887 7.54892 9.06379 7.28227 9.21609 6.974L11.5251 2.295Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun StarSolidPreview() {
    Icon(
        imageVector = InstUIIcons.Custom.StarSolid,
        contentDescription = "StarSolid",
        modifier = Modifier.size(48.dp),
    )
}
