/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.TextColor: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.TextColor",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M7.5 12.9988L11.539 3.30882C11.577 3.21772 11.6411 3.13991 11.7232 3.08517C11.8053 3.03043 11.9018 3.00122 12.0005 3.00122C12.0992 3.00122 12.1957 3.03043 12.2778 3.08517C12.3599 3.13991 12.424 3.21772 12.462 3.30882L16.5 12.9988M8.80402 9.99878H15.196M5 17H19C20.1046 17 21 17.8954 21 19C21 20.1046 20.1046 21 19 21H5C3.89543 21 3 20.1046 3 19C3 17.8954 3.89543 17 5 17Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun TextColorPreview() {
    Icon(
        imageVector = InstUIIcons.Custom.TextColor,
        contentDescription = "TextColor",
        modifier = Modifier.size(48.dp),
    )
}
