/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.ThumbsUpSolid: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.ThumbsUpSolid",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M7 9.98542V22H17.5C17.9327 22 18.3538 21.8596 18.7 21.6C19.0462 21.3404 19.2988 20.9754 19.42 20.56L21.75 12.56C21.8369 12.2619 21.8533 11.9477 21.7977 11.6422C21.7422 11.3367 21.6163 11.0484 21.43 10.8C21.2437 10.5516 21.0021 10.35 20.7244 10.2111C20.4467 10.0723 20.1405 10 19.83 10H14L15 5.88C15.113 5.42213 15.1212 4.94464 15.0237 4.4832C14.9263 4.02176 14.7259 3.5883 14.4374 3.2152C14.1489 2.84211 13.7799 2.53902 13.3578 2.3286C12.9357 2.11817 12.4716 2.00584 12 2L8.55 8.89C8.38442 9.22321 8.12917 9.50363 7.81296 9.69972C7.56514 9.85339 7.28757 9.9505 7 9.98542Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M7 9.98542V22H17.5M7 9.98542C7.28757 9.9505 7.56514 9.85339 7.81296 9.69972M7 9.98542L6.96188 9.98968M17.5 22C17.9327 22 18.3538 21.8596 18.7 21.6C19.0462 21.3404 19.2988 20.9754 19.42 20.56L21.75 12.56C21.8369 12.2619 21.8533 11.9477 21.7977 11.6422C21.7422 11.3367 21.6163 11.0484 21.43 10.8C21.2437 10.5516 21.0021 10.35 20.7244 10.2111C20.4467 10.0723 20.1405 10 19.83 10H14L15 5.88C15.113 5.42213 15.1212 4.94464 15.0237 4.4832C14.9263 4.02176 14.7259 3.5883 14.4374 3.2152C14.1489 2.84211 13.7799 2.53902 13.3578 2.3286C12.9357 2.11817 12.4716 2.00584 12 2L8.55 8.89C8.38442 9.22321 8.12917 9.50363 7.81296 9.69972M17.5 22H4C3.46957 22 2.96086 21.7893 2.58579 21.4142C2.21071 21.0391 2 20.5304 2 20V12C2 11.4696 2.21071 10.9609 2.58579 10.5858C2.96086 10.2107 3.46957 10 4 10H6.76C6.82762 9.99996 6.89499 9.9965 6.96188 9.98968M7.81296 9.69972C7.5542 9.86018 7.26302 9.95896 6.96188 9.98968"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
