/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.custom

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Custom.UserRoundLock: ImageVector by lazy {
    ImageVector.Builder(
        name = "Custom.UserRoundLock",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M2 21.0002C2.00012 19.7412 2.29739 18.5 2.86766 17.3775C3.43792 16.255 4.26506 15.283 5.28182 14.5404C6.29858 13.7979 7.47624 13.3058 8.71904 13.1042C9.96183 12.9026 11.2347 12.9972 12.434 13.3802M19.25 16.5558V14.778C19.25 14.3065 19.0656 13.8543 18.7374 13.5209C18.4092 13.1875 17.9641 13.0002 17.5 13.0002C17.0359 13.0002 16.5908 13.1875 16.2626 13.5209C15.9344 13.8543 15.75 14.3065 15.75 14.778V16.5558M15 8C15 10.7614 12.7614 13 10 13C7.23858 13 5 10.7614 5 8C5 5.23858 7.23858 3 10 3C12.7614 3 15 5.23858 15 8ZM14.875 16.5558H20.125C20.6082 16.5558 21 16.9538 21 17.4447V20.1114C21 20.6023 20.6082 21.0002 20.125 21.0002H14.875C14.3918 21.0002 14 20.6023 14 20.1114V17.4447C14 16.9538 14.3918 16.5558 14.875 16.5558Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun UserRoundLockPreview() {
    Icon(
        imageVector = InstUIIcons.Custom.UserRoundLock,
        contentDescription = "UserRoundLock",
        modifier = Modifier.size(48.dp),
    )
}
