/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.AiInfo: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.AiInfo",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M900.68 1005.14H791.34L846.01 815.57L900.68 1005.14Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M960 0C1489.35 0 1920 430.645 1920 960C1920 1489.35 1489.35 1920 960 1920C430.645 1920 0 1489.35 0 960C0 430.645 430.645 0 960 0ZM774.3 725.4L613.84 1194H736.67L768.62 1088.21H923.399L954.64 1194H1080.31L920.56 725.4H774.3ZM1135.01 725.4V1194H1257.13V725.4H1135.01Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun AiInfoPreview() {
    Icon(
        imageVector = InstUIIcons.Solid.AiInfo,
        contentDescription = "AiInfo",
        modifier = Modifier.size(48.dp),
    )
}
