/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.ChartPie: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.ChartPie",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1916.71 880C1916.21 873.932 1915.66 867.88 1915.04 861.845 1869.31 411.518 1512.33 53.2039 1062.61 5.41895 1055.1 4.62088 1047.56 3.90946 1040 3.28564V880H1916.71ZM880 3.28564V926.862L226.955 1579.91C86.6134 1414.12 1.50085 1200.08.0196554 966.208.00655833 964.14 0 962.071 0 960 0 496.081 329.071 109.02 766.527 19.5035 803.617 11.9137 841.486 6.46298 880 3.28564ZM340.092 1693.04C343.162 1695.64 346.248 1698.22 349.351 1700.78 515.295 1837.73 728.04 1920 960 1920 1463.25 1920 1876.06 1532.76 1916.71 1040H993.137L340.092 1693.04Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun ChartPiePreview() {
    Icon(
        imageVector = InstUIIcons.Solid.ChartPie,
        contentDescription = "ChartPie",
        modifier = Modifier.size(48.dp),
    )
}
