/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.Compose: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.Compose",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "m1108.675 239.002-837.6 838.368a96.377 96.377 0 0 0-26.304 49.056l-99.84 499.2c-6.24 31.488 3.552 64.032 26.208 86.784 18.24 18.144 42.72 28.128 67.968 28.128 6.24 0 12.48-.672 18.816-1.92l499.2-99.84a96.94 96.94 0 0 0 49.056-26.208l825.792-825.216v1083.648h-1632v-1632h1108.704ZM1442.9 40.33c54.624-53.76 149.76-53.76 203.52 0l196.8 196.8a143.766 143.766 0 0 1 42.144 101.76c0 38.4-15.264 74.88-42.144 101.76l-199.68 198.72-905.376 905.28-499.104 99.84 99.84-499.2 905.28-905.28Zm-977.376 1113.6-38.304 38.4-66.24 330.24 330.24-66.24 38.304-38.4-264-264Zm840-644.16L712.34 1103.05l68.16 68.16 593.28-593.28-68.256-68.16ZM1544.66 94.09c-12.48 0-24.96 5.76-33.6 14.4l-131.52 131.52 264 264 131.52-131.52c8.64-8.64 14.304-21.12 14.304-33.6 0-13.44-5.664-24.96-14.304-34.56l-195.84-195.84c-9.696-8.64-21.12-14.4-34.56-14.4Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun ComposePreview() {
    Icon(
        imageVector = InstUIIcons.Solid.Compose,
        contentDescription = "Compose",
        modifier = Modifier.size(48.dp),
    )
}
