/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.MicOff: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.MicOff",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M666.286 1242.8c-88.168-79.79-143.65-195.06-143.65-323.033V435.679C522.636 195.475 718.111 0 958.315 0c176.955 0 329.645 106.09 397.775 257.997L1536.8 0l92.38 64.669L331.381 1917.48 239 1852.81l305.289-435.84C412.414 1301.53 329 1132.02 329 943.408V709.98h96.818v233.428c0 155.812 67.32 296.242 174.393 393.722l66.075-94.33Zm129.034 207.58-57.716 82.4c54.294 20.4 112.129 33.5 172.304 38.1v252.3H667.861V1920h580.909v-96.82h-242.044v-252.3c324.464-24.8 580.904-296.76 580.904-627.472V709.98h-96.82v233.428c0 293.552-238.94 532.492-532.495 532.492-56.824 0-111.601-8.95-162.995-25.52Zm598.67-854.695L868.36 1346.11c29.036 6.12 59.127 9.34 89.955 9.34 240.205 0 435.675-195.48 435.675-435.683V595.685Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
