/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.MiniArrowDouble: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.MiniArrowDouble",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
        autoMirror = true,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1319.1 790.054 1020.06 355.79C986.895 307.625 932.507 308.517 899.956 355.79L600.92 790.054C567.754 838.219 588.339 877.264 647.036 877.264H1272.98C1331.62 877.264 1351.65 837.326 1319.1 790.054ZM600.634 1129.94 899.669 1564.21C932.836 1612.37 987.223 1611.48 1019.77 1564.21L1318.81 1129.94C1351.98 1081.78 1331.39 1042.73 1272.69 1042.73L646.75 1042.73C588.114 1042.73 568.082 1082.67 600.634 1129.94Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun MiniArrowDoublePreview() {
    Icon(
        imageVector = InstUIIcons.Solid.MiniArrowDouble,
        contentDescription = "MiniArrowDouble",
        modifier = Modifier.size(48.dp),
    )
}
