/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.NextUnread: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.NextUnread",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "m0 524.664 878.039 812.43 592.454-557.236c48.603 25.014 101.924 40.484 158.207 43.007 5.815.22 11.41.33 17.225.33 38.29 0 74.606-7.132 109.495-17.555v857.633l-424.812-491.847-82.943 71.643 442.804 512.692H64.951l442.804-512.692-82.943-71.643L0 1663.273V524.663ZM1278.977 329.56c-8.777 29.622-15.47 60.232-16.786 92.598-4.608 102.473 30.939 200.557 100.278 276.26 5.376 5.924 11.85 10.312 17.554 15.798l-502.598 472.866L.044 375.091V329.56ZM1645.552 165c4.06 0 8.229.11 12.398.22 151.295 6.802 268.47 134.838 261.777 286.243-6.583 147.126-127.926 262.106-273.736 262.106-4.06 0-8.338-.11-12.507-.33-151.295-6.692-268.47-134.838-261.667-286.243C1378.29 279.87 1499.743 165 1645.552 165Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun NextUnreadPreview() {
    Icon(
        imageVector = InstUIIcons.Solid.NextUnread,
        contentDescription = "NextUnread",
        modifier = Modifier.size(48.dp),
    )
}
