/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.PeerGraded: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.PeerGraded",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M716.582 133c212.77 0 385.853 173.082 385.853 385.852v110.244c0 116.747-53.138 220.266-135.49 291.153 59.752 7.165 119.284 16.205 178.264 28.553 166.798 35.167 287.956 194.249 287.956 378.355v211.778l-22.49 16.536c-120.937 88.746-367.22 232.393-694.974 232.393-17.198 0-34.837-.44-52.476-1.212-288.838-13.56-507.892-133.174-640.846-231.291L0 1538.825v-211.778C0 1142.94 121.268 983.859 288.176 948.69c58.65-12.237 117.96-21.718 177.492-28.994-82.02-70.776-134.938-174.074-134.938-290.601V518.852C330.73 306.082 503.813 133 716.582 133ZM625.08 463.73c-97.675 0-116.858 71.99-184.106 99.22v66.146c0 151.915 123.583 275.608 275.608 275.608 152.026 0 275.61-123.693 275.61-275.608V518.852c0-2.536-.662-4.96-.773-7.607-2.956 2.68-5.884 5.384-8.813 8.088l-1.952 1.803c-28.97 26.728-58.555 52.838-116.345 52.838-120.166 0-120.166-110.244-239.229-110.244Zm1216.978-156.115-353.771 353.77-157.428-157.427-77.942 77.942 235.37 235.37L1920 385.557l-77.942-77.942Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun PeerGradedPreview() {
    Icon(
        imageVector = InstUIIcons.Solid.PeerGraded,
        contentDescription = "PeerGraded",
        modifier = Modifier.size(48.dp),
    )
}
