/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.PostToSis: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.PostToSis",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M922.293 1188.96c20.8-20.8 54.614-20.8 75.414 0l266.666 266.667-75.413 75.413-175.573-175.573v564.586H906.72v-564.586L731.04 1531.04l-75.413-75.413ZM1600-.043c88.213 0 160 71.787 160 160v746.667c0 88.32-71.787 160-160 160H320c-88.213 0-160-71.68-160-160V159.957c0-88.213 71.787-160 160-160Zm-68.587 306.134c-70.826-73.067-186.986-109.12-275.84-85.547-62.826 16.427-106.56 59.733-122.986 121.813-34.667 131.2 99.84 213.654 185.066 241.92 1.174.427 132.907 46.614 113.494 111.68-7.574 25.707-23.68 40.854-50.667 47.36-51.52 13.014-125.76-12.16-169.067-56.533l-76.373 74.347c56.427 58.026 139.093 92.266 215.68 92.266 19.093 0 37.653-2.026 55.36-6.4 63.68-15.786 108.907-58.56 127.36-120.64 39.253-132.053-96.32-215.253-182.507-243.413-1.386-.427-132.693-47.147-115.2-113.28 6.614-24.64 21.44-39.36 46.827-45.973 51.307-13.227 128.853 11.84 172.48 56.746Zm-746.666 0c-70.827-73.067-187.094-109.12-275.84-85.547-62.827 16.427-106.56 59.733-122.987 121.813-34.667 131.2 99.84 213.654 185.067 241.92 1.173.427 132.906 46.614 113.493 111.68-7.573 25.707-23.68 40.854-50.667 47.36-51.306 13.014-125.76-12.16-169.066-56.533l-76.374 74.347c56.427 58.026 139.094 92.266 215.68 92.266 19.094 0 37.654-2.026 55.36-6.4 63.68-15.786 108.907-58.56 127.36-120.64 39.254-132.053-96.32-215.253-182.506-243.413-1.387-.427-132.694-47.147-115.2-113.28 6.613-24.64 21.44-39.36 46.826-45.973 51.52-13.227 128.747 11.84 172.48 56.746Zm228.586-92.8H906.667v640h106.666v-640Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
