/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.Protractor: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.Protractor",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M960 480.667c-530.193 0-960 429.807-960 960.003h1920c0-530.196-429.81-960.003-960-960.003ZM1261.79 1334c-43.93-124.29-162.46-213.33-301.79-213.33-132.548 0-246.274 80.59-294.853 195.44a315.89 315.89 0 0 0-6.938 17.89h603.581ZM1232 886.001c44.18 0 80-35.818 80-80 0-44.183-35.82-80-80-80s-80 35.817-80 80c0 44.182 35.82 80 80 80Zm-464-80c0 44.182-35.818 80-80 80-44.183 0-80-35.818-80-80 0-44.183 35.817-80 80-80 44.182 0 80 35.817 80 80Zm677.33 229.333c44.19 0 80-35.818 80-80 0-44.183-35.81-80-80-80-44.18 0-80 35.817-80 80 0 44.182 35.82 80 80 80Zm208 143.996c0 44.19-35.81 80-80 80-44.18 0-80-35.81-80-80 0-44.18 35.82-80 80-80 44.19 0 80 35.82 80 80ZM474.666 1035.334c44.183 0 80-35.818 80-80 0-44.183-35.817-80-80-80-44.182 0-80 35.817-80 80 0 44.182 35.818 80 80 80Zm-47.999 143.996c0 44.19-35.818 80-80 80-44.183 0-80-35.81-80-80 0-44.18 35.817-80 80-80 44.182 0 80 35.82 80 80ZM960 827.334c44.18 0 80-35.818 80-80 0-44.183-35.82-80-80-80-44.183 0-80 35.817-80 80 0 44.182 35.817 80 80 80Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun ProtractorPreview() {
    Icon(
        imageVector = InstUIIcons.Solid.Protractor,
        contentDescription = "Protractor",
        modifier = Modifier.size(48.dp),
    )
}
