/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.QuizStatsDeviation: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.QuizStatsDeviation",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M677.647 872.098v175.85c0 107.18 87.19 194.371 194.485 194.371h62.795c107.294 0 194.485-87.19 194.485-194.372v-175.85c0-107.18-87.19-194.484-194.485-194.484h-62.795c-107.294 0-194.485 87.304-194.485 194.485m734.118-194.45h-240.678c43.821 53.194 71.266 120.281 71.266 194.484v175.736c0 169.525-137.901 307.426-307.426 307.426h-62.795c-169.525 0-307.426-137.901-307.426-307.426V872.132c0-169.525 137.901-307.426 307.426-307.426h539.633v112.941ZM960 0C430.645 0 0 430.645 0 960s430.645 960 960 960 960-430.645 960-960S1489.355 0 960 0Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun QuizStatsDeviationPreview() {
    Icon(
        imageVector = InstUIIcons.Solid.QuizStatsDeviation,
        contentDescription = "QuizStatsDeviation",
        modifier = Modifier.size(48.dp),
    )
}
