/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.SisNotSynced: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.SisNotSynced",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M960 0c529.28 0 960 430.613 960 960s-430.72 960-960 960S0 1489.387 0 960c0-239.04 88.64-465.92 244.48-640H53.333V106.667H640v586.666H426.667v-254.08C291.733 577.387 213.333 762.987 213.333 960c0 411.627 334.934 746.667 746.667 746.667s746.667-335.04 746.667-746.667S1371.733 213.333 960 213.333Zm191.253 671.253L1302.08 822.08l-191.253 191.253 191.253 191.254-150.827 150.826L960 1164.16l-191.253 191.253-150.827-150.826 191.253-191.254L617.92 822.08l150.827-150.827L960 862.507l191.253-191.254Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
