/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.Table: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.Table",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1694.344 1355.294v338.824h-339.05v-338.824h339.05Zm-564.932 0v338.824H790.588v-338.824h338.824Zm-564.706 0v338.824H225.882v-338.824h338.824Zm564.706-564.706v338.824H790.588V790.588h338.824Zm-564.706 0v338.824H225.882V790.588h338.824Zm1129.525 0v338.824h-338.937V790.588h338.937Zm-564.82-564.706v338.824H790.589V225.882h338.824Zm-564.705 0v338.824H225.882V225.882h338.824Zm1129.412 0v338.824h-338.824V225.882h338.824Zm0-225.882H225.882C101.308 0 0 101.308 0 225.882v1468.236C0 1818.692 101.308 1920 225.882 1920h1468.236c124.574 0 225.882-101.308 225.882-225.882V225.882C1920 101.308 1818.692 0 1694.118 0Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
