/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.solid

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Solid.Undo: ImageVector by lazy {
    ImageVector.Builder(
        name = "Solid.Undo",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
        autoMirror = true,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M640.001 98.75L810.909 269.658L468.005 612.563H1316.66V854.301H457.368L810.909 1207.96L640.001 1378.87L0.000127157 738.75L640.001 98.75Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1316.66 854.301C1517.02 854.752 1678.43 1017.35 1678.44 1217.81C1678.44 1418.28 1516.19 1580.8 1315.83 1581.25V1821.25C1476.06 1821.24 1629.72 1757.57 1743.02 1644.27C1856.32 1530.97 1919.99 1377.31 1920 1217.08C1920 1056.84 1856.33 903.103 1743.02 789.792C1629.72 676.495 1476.89 612.575 1316.66 612.563V854.301Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun UndoPreview() {
    Icon(
        imageVector = InstUIIcons.Solid.Undo,
        contentDescription = "Undo",
        modifier = Modifier.size(48.dp),
    )
}
