/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.primitives

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * InstUI Size Primitives.
 *
 * Spacing and sizing values converted from rem to dp (1rem = 16dp).
 * Fractional values are preserved (e.g., size2_5 = 2.5.dp).
 */
object InstUISizes {
    val size1 = 1.dp
    val size1_25 = 1.25.dp
    val size1_5 = 1.5.dp
    val size2 = 2.dp
    val size2_5 = 2.5.dp
    val size3 = 3.dp
    val size4 = 4.dp
    val size8 = 8.dp
    val size12 = 12.dp
    val size14 = 14.dp
    val size16 = 16.dp
    val size20 = 20.dp
    val size24 = 24.dp
    val size28 = 28.dp
    val size32 = 32.dp
    val size36 = 36.dp
    val size40 = 40.dp
    val size48 = 48.dp
    val size64 = 64.dp
}
