/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.primitives

import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import com.instructure.instui.R

/**
 * InstUI Font Family Primitives.
 *
 * Font families from the InstUI design system.
 *
 * IMPORTANT: Font files must be manually added to res/font/ directory.
 * The generator creates references to font resources that must exist.
 *
 * If a requested font weight is not available, Android will use the
 * closest available weight (e.g., requesting 200 with only 400 available
 * will use 400).
 */
object InstUIFontFamilies {
    /**
     * Atkinson Hyperlegible Next typeface.
     * CSS: Atkinson Hyperlegible Next, "Helvetica Neue", Helvetica, Arial, sans-serif
     *
     * Note: Font files must be added to res/font/ directory.
     * Expected: atkinson_hyperlegible_next_extralight.ttf, atkinson_hyperlegible_next_light.ttf, atkinson_hyperlegible_next_regular.ttf, atkinson_hyperlegible_next_medium.ttf, atkinson_hyperlegible_next_semibold.ttf, atkinson_hyperlegible_next_bold.ttf, atkinson_hyperlegible_next_extrabold.ttf
     */
    val atkinson = FontFamily(
        Font(R.font.atkinson_hyperlegible_next_extralight, weight = FontWeight.ExtraLight),
        Font(R.font.atkinson_hyperlegible_next_light, weight = FontWeight.Light),
        Font(R.font.atkinson_hyperlegible_next_regular, weight = FontWeight.Normal),
        Font(R.font.atkinson_hyperlegible_next_medium, weight = FontWeight.Medium),
        Font(R.font.atkinson_hyperlegible_next_semibold, weight = FontWeight.SemiBold),
        Font(R.font.atkinson_hyperlegible_next_bold, weight = FontWeight.Bold),
        Font(R.font.atkinson_hyperlegible_next_extrabold, weight = FontWeight.ExtraBold),
    )

    /**
     * Inclusive Sans typeface.
     * CSS: Inclusive Sans, "Helvetica Neue", Helvetica, Arial, sans-serif
     *
     * Note: Font files must be added to res/font/ directory.
     * Expected: inclusive_sans_light.ttf, inclusive_sans_regular.ttf, inclusive_sans_medium.ttf, inclusive_sans_semibold.ttf, inclusive_sans_bold.ttf
     */
    val inclusiveSans = FontFamily(
        Font(R.font.inclusive_sans_light, weight = FontWeight.Light),
        Font(R.font.inclusive_sans_regular, weight = FontWeight.Normal),
        Font(R.font.inclusive_sans_medium, weight = FontWeight.Medium),
        Font(R.font.inclusive_sans_semibold, weight = FontWeight.SemiBold),
        Font(R.font.inclusive_sans_bold, weight = FontWeight.Bold),
    )

    /**
     * Lato typeface.
     * CSS: Lato, "Helvetica Neue", Helvetica, Arial, sans-serif
     *
     * Note: Font files must be added to res/font/ directory.
     * Expected: lato_thin.ttf, lato_light.ttf, lato_regular.ttf, lato_bold.ttf, lato_black.ttf
     */
    val lato = FontFamily(
        Font(R.font.lato_thin, weight = FontWeight.Thin),
        Font(R.font.lato_light, weight = FontWeight.Light),
        Font(R.font.lato_regular, weight = FontWeight.Normal),
        Font(R.font.lato_bold, weight = FontWeight.Bold),
        Font(R.font.lato_black, weight = FontWeight.Black),
    )

    /**
     * Monospace font.
     * CSS: Menlo, Consolas, Monaco, "Andale Mono", monospace
     * Uses system monospace font on Android.
     */
    val menlo = FontFamily.Monospace
}
