/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.AddMedia: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.AddMedia",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1493.33 320V0H1600v320h320v106.667h-320v320h-106.67v-320h-320V320h320ZM160 426.667c-29.455 0-53.333 23.878-53.333 53.333v1280c0 29.46 23.878 53.33 53.333 53.33h1280c29.46 0 53.33-23.87 53.33-53.33V960H1600v800c0 88.37-71.63 160-160 160H160c-88.365 0-160-71.63-160-160V480c0-88.366 71.634-160 160-160h800v106.667H160Zm373.333 279.136L1223.66 1120l-690.327 414.2V705.803ZM640 894.197V1345.8l376.34-225.8L640 894.197Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
