/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.Android: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.Android",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M535.056 9.512c25.75-17.28 60.987-10.39 78.38 15.586l94.304 141.061c59.859-25.976 123.782-44.61 191.885-50.597a671.282 671.282 0 0 1 314.085 48.226l92.385-138.577c17.167-26.09 52.178-32.979 78.267-15.699 25.976 17.28 32.979 52.404 15.699 78.267l-85.721 128.639c29.251 18.86 57.373 39.415 83.123 63.02 118.474 108.535 183.753 253.324 183.753 407.6v734.107c0 88.206-76.008 160.036-169.41 160.036h-169.409V1920h-112.94v-338.82H790.638V1920h-112.94v-338.82H508.29c-93.401 0-169.41-71.829-169.41-160.035V709.286c0-200.468 107.293-380.268 269.249-488.916L519.583 87.892c-17.393-25.863-10.39-60.987 15.473-78.38Zm424.427 216.392c-16.602 0-33.317.791-50.032 2.26-256.6 22.474-457.632 233.784-457.632 481.122v711.86c0 25.863 25.299 47.095 56.47 47.095h903.518c31.17 0 56.47-21.232 56.47-47.096V687.037c0-122.313-52.179-237.512-147.161-324.363-96.112-88.205-225.766-136.77-361.633-136.77ZM113 1298.832h112.94V734.133H113v564.699Zm1581.156 0h112.94V734.133h-112.94v564.699ZM734.168 474.394c-49.919 0-90.351 40.433-90.351 90.352 0 49.807 40.432 90.352 90.351 90.352 49.92 0 90.352-40.545 90.352-90.352 0-49.92-40.432-90.352-90.352-90.352m451.76 0c-49.92 0-90.353 40.433-90.353 90.352 0 49.807 40.433 90.352 90.352 90.352 49.92 0 90.352-40.545 90.352-90.352 0-49.92-40.432-90.352-90.352-90.352"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun AndroidPreview() {
    Icon(
        imageVector = InstUIIcons.Line.Android,
        contentDescription = "Android",
        modifier = Modifier.size(48.dp),
    )
}
