/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.ClosedCaptioning: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.ClosedCaptioning",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1800 1745V185c0-33-27-60-60-60H180c-33 0-60 27-60 60v1560c0 33 27 60 60 60h1560c33 0 60-27 60-60ZM1740 5c99.24 0 180 80.76 180 180v1560c0 99.24-80.76 180-180 180H180c-99.24 0-180-80.76-180-180V185C0 85.76 80.76 5 180 5h1560ZM859.522 853.669h-160v-53.333H486.189v320h213.333v-53.334h160v106.667c0 58.667-48 106.667-106.667 106.667h-320c-58.666 0-106.666-48-106.666-106.667V747.002c0-58.666 48-106.666 106.666-106.666h320c58.667 0 106.667 48 106.667 106.666V853.67Zm725 0h-160v-53.333h-213.333v320h213.333v-53.334h160v106.667c0 58.667-48 106.667-106.667 106.667h-320c-58.666 0-106.666-48-106.666-106.667V747.002c0-58.666 48-106.666 106.666-106.666h320c58.667 0 106.667 48 106.667 106.666V853.67Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun ClosedCaptioningPreview() {
    Icon(
        imageVector = InstUIIcons.Line.ClosedCaptioning,
        contentDescription = "ClosedCaptioning",
        modifier = Modifier.size(48.dp),
    )
}
