/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.Compare: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.Compare",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M53.3333 1620C23.8781 1620 -3.5125e-07 1596.12 0 1566.67L2.16238e-05 53.3334C2.1975e-05 23.8782 23.8782 -3.5125e-07 53.3334 0L853.333 9.5399e-06C882.788 9.89115e-06 906.667 23.8782 906.667 53.3334V1566.67C906.667 1596.12 882.788 1620 853.333 1620H53.3333ZM149.333 1513.33C125.769 1513.33 106.667 1494.23 106.667 1470.67L106.667 149.333C106.667 125.769 125.769 106.667 149.333 106.667H757.333C780.897 106.667 800 125.769 800 149.333V1470.67C800 1494.23 780.897 1513.33 757.333 1513.33H149.333Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1066.67 1920C1037.21 1920 1013.33 1896.12 1013.33 1866.67V353.333C1013.33 323.878 1037.21 300 1066.67 300L1866.67 300C1896.12 300 1920 323.878 1920 353.333V1866.67C1920 1896.12 1896.12 1920 1866.67 1920H1066.67ZM1162.67 1813.33C1139.1 1813.33 1120 1794.23 1120 1770.67V449.333C1120 425.769 1139.1 406.667 1162.67 406.667L1770.67 406.667C1794.23 406.667 1813.33 425.769 1813.33 449.333V1770.67C1813.33 1794.23 1794.23 1813.33 1770.67 1813.33H1162.67Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M495.892 1050L420.799 974.854L542.573 853.133L164.134 853.133V746.867L542.573 746.867L420.799 625.146L495.892 550L745.866 800.027L495.892 1050Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1415.11 838L1490.2 913.146L1368.43 1034.87H1746.87V1141.13H1368.43L1490.2 1262.85L1415.11 1338L1165.13 1087.97L1415.11 838Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun ComparePreview() {
    Icon(
        imageVector = InstUIIcons.Line.Compare,
        contentDescription = "Compare",
        modifier = Modifier.size(48.dp),
    )
}
