/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.Flag: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.Flag",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1848.715 357.685c-13.891-15.586-35.35-22.137-55.793-17.167-419.802 105.035-630.324-19.087-833.844-139.03C756.46 82.333 547.52-40.66 168.94 103.905V0H56v1920h112.941V227.012c352.941-148.97 522.127-52.292 732.763 71.83 195.84 115.313 415.849 245.083 811.82 174.156-170.88 375.53-385.92 382.87-652.912 392.131-233.788 8.02-498.748 17.28-762.24 280.772l79.85 79.963c232.093-232.095 463.058-240 686.343-247.906 290.823-10.052 591.473-20.443 794.88-562.786 7.34-19.652 3.275-41.788-10.73-57.487"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun FlagPreview() {
    Icon(
        imageVector = InstUIIcons.Line.Flag,
        contentDescription = "Flag",
        modifier = Modifier.size(48.dp),
    )
}
