/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.GradebookExport: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.GradebookExport",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "m0 1016.081 409.186 409.073 79.85-79.736-272.867-272.979h1136.415V959.611H216.169l272.866-272.866-79.85-79.85L0 1016.082ZM1465.592 305.32l315.445 315.445h-315.445V305.32Zm402.184 242.372-329.224-329.11C1507.042 187.07 1463.334 169 1418.835 169h-743.83v677.647h112.94V281.941h564.706v451.765h451.765v903.53H787.946V1185.47H675.003v564.705h1242.353V667.522c0-44.498-18.07-88.207-49.581-119.83Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
