/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.MoveUpTop: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.MoveUpTop",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1920 1672.031v106.67H533.303v-106.67H1920ZM357.661 141l304.434 304.327L357.66 749.76l-75.308-75.521L457.93 498.66H106.562v1280.03H0V392.099h457.93l-175.577-175.79L357.66 141ZM1920 1245.249v106.775H533.303V1245.25H1920Zm0-426.57v106.67H533.303v-106.67H1920Zm-853.352-426.676v106.669H853.31v-106.67h213.338Zm426.676 0v106.669h-213.338v-106.67h213.338Zm426.676 0v106.669h-213.338v-106.67H1920Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun MoveUpTopPreview() {
    Icon(
        imageVector = InstUIIcons.Line.MoveUpTop,
        contentDescription = "MoveUpTop",
        modifier = Modifier.size(48.dp),
    )
}
