/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.NextUnread: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.NextUnread",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M0 373.397v1386.667h1706.667v-803.2H1600v602.56l-305.6-366.827-82.027 68.267 327.04 392.533H167.253l327.04-392.533-82.026-68.267-305.6 366.827v-897.6l746.666 690.88 490.56-453.76-72.32-78.4-418.24 386.773-746.666-690.88v-36.373H1123.2V373.397H0Zm1383.957-129.525c63.147-57.707 145.494-87.36 230.294-83.52 85.333 3.84 164.16 40.64 221.866 103.68 57.707 63.04 87.36 144.853 83.52 230.293-3.733 85.334-40.533 164.16-103.68 221.867-59.413 54.4-135.573 83.84-215.573 83.84-4.907 0-9.707-.107-14.613-.32-85.44-3.84-164.16-40.64-221.867-103.68-57.707-63.04-87.36-144.853-83.627-230.293 3.84-85.334 40.64-164.16 103.68-221.867Zm215.787 22.827c-53.333 0-104.107 19.626-143.68 55.893-42.133 38.507-66.667 90.987-69.227 147.947-2.56 56.96 17.28 111.36 55.68 153.493 38.507 42.027 91.094 66.56 148.054 69.12 56.853 2.88 111.36-17.28 153.386-55.68 42.134-38.507 66.667-91.093 69.12-147.947 2.56-56.96-17.173-111.466-55.68-153.493-38.4-42.027-90.986-66.56-147.946-69.12-3.2-.213-6.4-.213-9.707-.213Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun NextUnreadPreview() {
    Icon(
        imageVector = InstUIIcons.Line.NextUnread,
        contentDescription = "NextUnread",
        modifier = Modifier.size(48.dp),
    )
}
