/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.QuizStatsDeviation: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.QuizStatsDeviation",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M960 1807.059c-467.125 0-847.059-379.934-847.059-847.059 0-467.125 379.934-847.059 847.059-847.059 467.125 0 847.059 379.934 847.059 847.059 0 467.125-379.934 847.059-847.059 847.059M960 0C430.645 0 0 430.645 0 960s430.645 960 960 960 960-430.645 960-960S1489.355 0 960 0m169.412 1047.902c0 107.181-87.19 194.485-194.485 194.485h-62.795c-107.294 0-194.485-87.304-194.485-194.485v-175.85c0-107.18 87.19-194.371 194.485-194.371h62.795c107.294 0 194.485 87.19 194.485 194.372v175.85ZM960 567.224c-8.358-.677-16.49-2.484-25.073-2.484h-62.795c-169.525 0-307.426 137.788-307.426 307.313v175.85c0 169.524 137.901 307.425 307.426 307.425h62.795c169.525 0 307.426-137.901 307.426-307.426v-175.85c0-74.089-27.445-141.289-71.266-194.371h240.678V564.74H960v2.484Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun QuizStatsDeviationPreview() {
    Icon(
        imageVector = InstUIIcons.Line.QuizStatsDeviation,
        contentDescription = "QuizStatsDeviation",
        modifier = Modifier.size(48.dp),
    )
}
