/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.Restore: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.Restore",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M960 0V112.941C492.875 112.941 112.941 492.875 112.941 960C112.941 1427.12 492.875 1807.06 960 1807.06C1427.12 1807.06 1807.06 1427.12 1807.06 960C1807.06 692.894 1680.45 444.085 1468.24 284.273V677.647H1355.29V112.941H1920V225.882H1577.11C1792.94 407.379 1920 674.711 1920 960C1920 1489.36 1489.36 1920 960 1920C430.645 1920 0 1489.36 0 960C0 430.645 430.645 0 960 0Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M905.23 958.422L497.115 1264.57L564.961 1355.2L1018.31 1014.99V447.995H905.23V958.422Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun RestorePreview() {
    Icon(
        imageVector = InstUIIcons.Line.Restore,
        contentDescription = "Restore",
        modifier = Modifier.size(48.dp),
    )
}
