/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.ScreenCapture: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.ScreenCapture",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1706.67 106.667h-320V0h320C1824.49 0 1920 95.513 1920 213.333v320h-106.67v-320c0-58.91-47.75-106.666-106.66-106.666ZM533.333 0v106.667h-320c-58.91 0-106.666 47.756-106.666 106.666v320H0v-320C0 95.513 95.513 0 213.333 0h320ZM0 1386.67h106.667v320c0 58.91 47.756 106.66 106.666 106.66h320V1920h-320C95.513 1920 0 1824.49 0 1706.67v-320ZM1386.67 1920v-106.67h320c58.91 0 106.66-47.75 106.66-106.66v-320H1920v320c0 117.82-95.51 213.33-213.33 213.33h-320ZM1280 960c0 176.73-143.27 320-320 320-176.731 0-320-143.27-320-320 0-176.731 143.269-320 320-320 176.73 0 320 143.269 320 320Zm106.67 0c0 235.64-191.03 426.67-426.67 426.67-235.641 0-426.667-191.03-426.667-426.67 0-235.641 191.026-426.667 426.667-426.667 235.64 0 426.67 191.026 426.67 426.667Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun ScreenCapturePreview() {
    Icon(
        imageVector = InstUIIcons.Line.ScreenCapture,
        contentDescription = "ScreenCapture",
        modifier = Modifier.size(48.dp),
    )
}
