/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.Subaccounts: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.Subaccounts",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M1242.24 0v564.706h-225.77v301.101h677.648v489.487H1920V1920h-564.819v-564.706h225.995V978.861h-564.705v376.433h225.769V1920H677.647v-564.706H903.53V978.861H338.711v376.433h225.995V1920H0v-564.706h225.77V865.807h677.76V564.706H677.646V0h564.593Zm564.819 1468.348h-338.937v338.824h338.937v-338.824Zm-677.647 0H790.588v338.824h338.824v-338.824Zm-677.647 0H112.94v338.824h338.824v-338.824Zm677.647-1355.407H790.588v338.937h338.824V112.94Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun SubaccountsPreview() {
    Icon(
        imageVector = InstUIIcons.Line.Subaccounts,
        contentDescription = "Subaccounts",
        modifier = Modifier.size(48.dp),
    )
}
