/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.VideoCameraOff: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.VideoCameraOff",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "m1421.141 2.417 91.775 64.262L215.481 1918.962l.595.416-.378.54-92.37-64.678L246.074 1680H0V240h1254.726L1421.141 2.416Zm79.395 278.487V678.89L1920 346.052v1228.01l-419.464-332.951V1680H520.538l76.895-109.78 793.325.001v-556.235l177.995 141.29 241.468 191.548V573.176l-241.468 191.662-177.995 141.29-.001-468.498 109.779-156.726Zm-322.705 68.874H109.779v1220.443h213.19l854.862-1220.443Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun VideoCameraOffPreview() {
    Icon(
        imageVector = InstUIIcons.Line.VideoCameraOff,
        contentDescription = "VideoCameraOff",
        modifier = Modifier.size(48.dp),
    )
}
