/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.Windows: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.Windows",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "m677.647 1642.605-564.706-78.268V1129.4h564.706v513.205Zm56.47-626.146H56.472c-31.172 0-56.471 25.3-56.471 56.47v540.537c0 28.236 20.781 52.066 48.79 55.906l677.648 93.967c2.484.452 5.195.565 7.68.565 13.553 0 26.654-4.856 37.044-13.892 12.31-10.73 19.426-26.202 19.426-42.579V1072.93c0-31.172-25.299-56.47-56.47-56.47Zm37.045-846.483c-12.31-10.729-28.574-15.811-44.724-13.327L48.79 250.616C20.78 254.456 0 278.287 0 306.522V847.06c0 31.172 25.299 56.47 56.47 56.47h677.648c31.171 0 56.47-25.298 56.47-56.47V212.555c0-16.376-7.115-31.85-19.426-42.579Zm-93.515 620.612H112.941V355.652l564.706-78.268v513.204Zm1223.04-776.583c-12.198-10.843-28.8-15.7-44.725-13.553l-903.53 123.332c-28.008 3.84-48.903 27.783-48.903 56.018V847.06c0 31.172 25.3 56.47 56.471 56.47h903.53c31.171 0 56.47-25.298 56.47-56.47V56.47c0-16.377-7.115-31.85-19.313-42.466Zm-93.628 776.583H1016.47V229.045l790.588-107.86v669.403Zm56.47 225.905H960c-31.172 0-56.47 25.186-56.47 56.47v667.257c0 28.236 20.894 52.066 48.903 56.02l903.53 123.218c2.484.339 5.082.565 7.566.565 13.553 0 26.767-4.97 37.158-14.005 12.198-10.73 19.313-26.202 19.313-42.466v-790.588c0-31.285-25.299-56.47-56.47-56.47Zm-56.47 782.344-790.588-107.972v-561.43h790.588v669.402Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}
