/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by the InstUI icon generator
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.icon.line

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.icon.InstUIIcons

val InstUIIcons.Line.ZoomIn: ImageVector by lazy {
    ImageVector.Builder(
        name = "Line.ZoomIn",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 1920f,
        viewportHeight = 1920f,
    )
    .addPath(
        pathData = PathParser().parsePathString(
            "M854.397 1594.874c-408.288 0-740.477-332.19-740.477-740.477 0-408.288 332.189-740.477 740.477-740.477 408.287 0 740.477 332.189 740.477 740.477 0 408.287-332.19 740.477-740.477 740.477ZM1920 1839.345l-423.325-423.211c131.577-150.488 212.118-346.543 212.118-561.737C1708.793 383.225 1325.568 0 854.397 0 383.225 0 0 383.225 0 854.397c0 471.17 383.225 854.396 854.397 854.396 215.08 0 411.363-80.54 561.737-212.118L1839.345 1920l80.655-80.655ZM911.356 455.678h-113.92v341.759H455.679v113.92h341.759v341.758h113.92V911.356h341.758v-113.92h-341.76V455.679Z"
        ).toNodes(),
        fill = SolidColor(Color.Black),
        pathFillType = PathFillType.EvenOdd,
    )
    .build()
}

@Preview(showBackground = true)
@Composable
private fun ZoomInPreview() {
    Icon(
        imageVector = InstUIIcons.Line.ZoomIn,
        contentDescription = "ZoomIn",
        modifier = Modifier.size(48.dp),
    )
}
