/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.component

import androidx.compose.runtime.Composable
import com.instructure.instui.BorderStyle
import com.instructure.instui.semantic.InstUILayoutTypography
import com.instructure.instui.semantic.InstUISemanticColors

/**
 * InstUI View component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIView {
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
    val color @Composable get() = InstUISemanticColors.Text.base()
    val colorPrimaryInverse @Composable get() = InstUISemanticColors.Text.inverse()
    val borderColorPrimary @Composable get() = InstUISemanticColors.Stroke.muted()
    val borderColorSecondary @Composable get() = InstUISemanticColors.Stroke.base()
    val borderColorSuccess @Composable get() = InstUISemanticColors.Stroke.success()
    val borderColorBrand @Composable get() = InstUISemanticColors.Stroke.brand()
    val borderColorInfo @Composable get() = InstUISemanticColors.Stroke.info()
    val borderColorAlert @Composable get() = InstUISemanticColors.Stroke.info()
    val borderColorWarning @Composable get() = InstUISemanticColors.Stroke.warning()
    val borderColorDanger @Composable get() = InstUISemanticColors.Stroke.error()
    val borderColorTransparent = "#00000000"
    val debugOutlineColor @Composable get() = InstUISemanticColors.Stroke.error()
    val backgroundPrimary @Composable get() = InstUISemanticColors.Background.ElevatedSurface.base()
    val backgroundSecondary @Composable get() = InstUISemanticColors.Background.muted()
    val backgroundPrimaryInverse @Composable get() = InstUISemanticColors.Background.ElevatedSurface.inverse()
    val backgroundBrand @Composable get() = InstUISemanticColors.Background.brand()
    val backgroundInfo @Composable get() = InstUISemanticColors.Background.info()
    val backgroundAlert @Composable get() = InstUISemanticColors.Background.info()
    val backgroundSuccess @Composable get() = InstUISemanticColors.Background.success()
    val backgroundDanger @Composable get() = InstUISemanticColors.Background.error()
    val backgroundWarning @Composable get() = InstUISemanticColors.Background.warning()
    val stackingTopmost = "9999"
    val stackingAbove = "1"
    val stackingBelow = "-1"
    val stackingDeepest = "-9999"
    val borderStyle = BorderStyle.Solid
}
