/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.sp
import com.instructure.instui.semantic.InstUILayoutSizes
import com.instructure.instui.semantic.InstUILayoutTypography
import com.instructure.instui.semantic.InstUISemanticColors

/**
 * InstUI Alert component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIAlert {
    val background @Composable get() = InstUISemanticColors.Background.ElevatedSurface.base()
    val borderRadius = InstUILayoutSizes.BorderRadius.Lg.lg
    val borderStyle = "solid"
    val borderWidth = InstUILayoutSizes.BorderWidth.Md.md
    val closeButtonMarginRight = "0.5rem"
    val closeButtonMarginTop = "0.5rem"
    val color @Composable get() = InstUISemanticColors.Text.base()
    val contentFontFamily = InstUILayoutTypography.FontFamily.Base.base
    val contentFontSize = 16.sp
    val contentFontWeight = InstUILayoutTypography.FontWeight.Body.base
    val contentLineHeight = InstUILayoutTypography.LineHeight.Standalone.base
    val dangerBorderColor @Composable get() = InstUISemanticColors.Stroke.error()
    val dangerIconBackground @Composable get() = InstUISemanticColors.Background.error()
    val iconColor @Composable get() = InstUISemanticColors.Icon.onColor()
    val infoBorderColor @Composable get() = InstUISemanticColors.Stroke.info()
    val infoIconBackground @Composable get() = InstUISemanticColors.Background.info()
    val successBorderColor @Composable get() = InstUISemanticColors.Stroke.success()
    val successIconBackground @Composable get() = InstUISemanticColors.Background.success()
    val warningBorderColor @Composable get() = InstUISemanticColors.Stroke.warning()
    val warningIconBackground @Composable get() = InstUISemanticColors.Background.warning()
    val contentPaddingVertical = InstUILayoutSizes.Spacing.SpaceMd.spaceMd
    val contentPaddingHorizontal = InstUILayoutSizes.Spacing.SpaceXl.spaceXl
}
