/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.instructure.instui.BorderStyle
import com.instructure.instui.semantic.InstUILayoutSizes
import com.instructure.instui.semantic.InstUILayoutTypography
import com.instructure.instui.semantic.InstUISemanticColors

/**
 * InstUI ToggleDetails component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIToggleDetails {
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
    val fontSizeLarge = 20.sp
    val fontSizeMedium = 16.sp
    val fontSizeSmall = 14.sp
    val fontWeight = InstUILayoutTypography.FontWeight.Body.base
    val iconMargin = 6.dp
    val lineHeight = InstUILayoutTypography.LineHeight.Paragraph.base
    val textColor @Composable get() = InstUISemanticColors.Text.base()
    val toggleBorderRadius = InstUILayoutSizes.BorderRadius.Interactive.base
    val toggleBorderStyle = BorderStyle.Solid
    val toggleBorderWidth = InstUILayoutSizes.BorderWidth.Md.md
    val togglePadding = 6.dp
    val contentPaddingSmall = 18.dp
    val contentPaddingMedium = 18.dp
    val contentPaddingLarge = 22.dp
}
