/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.sp
import com.instructure.instui.semantic.InstUILayoutTypography
import com.instructure.instui.semantic.InstUISemanticColors

/**
 * InstUI FormFieldMessage component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIFormFieldMessage {
    val hintTextColor @Composable get() = InstUISemanticColors.Text.muted()
    val errorTextColor @Composable get() = InstUISemanticColors.Text.error()
    val successTextColor @Composable get() = InstUISemanticColors.Text.success()
    val fontWeight = InstUILayoutTypography.FontWeight.Body.base
    val fontSize = 14.sp
    val lineHeight = InstUILayoutTypography.LineHeight.Paragraph.textSm
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
}
