/*
 * Copyright (C) 2022 - present Instructure, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.instructure.pandautils.analytics

const val SCREEN_VIEW_ACCOUNT_PREFERENCES = "account_preferences"
const val SCREEN_VIEW_ANNOUNCEMENT_LIST = "announcement_list"
const val SCREEN_VIEW_ANNOTATION_COMMENT_LIST = "annotation_comment_list"
const val SCREEN_VIEW_APPLICATION_SETTINGS = "application_settings"
const val SCREEN_VIEW_ASK_INSTRUCTOR = "ask_instructor"
const val SCREEN_VIEW_ASSIGNEE_LIST = "assignee_list"
const val SCREEN_VIEW_ASSIGNMENT_BASIC = "assignment_basic"
const val SCREEN_VIEW_ASSIGNMENT_DETAILS = "assignment_details"
const val SCREEN_VIEW_ASSIGNMENT_LIST = "assignment_list"
const val SCREEN_VIEW_ASSIGNMENT_SUBMISSION_LIST = "assignment_submission_list"
const val SCREEN_VIEW_ATTACHMENT_PICKER = "attachment_picker"
const val SCREEN_VIEW_ATTENDANCE_LIST = "attendance_list"
const val SCREEN_VIEW_BASIC_QUIZ = "basic_quiz"
const val SCREEN_VIEW_BOOKMARK_CREATION = "bookmark_creation"
const val SCREEN_VIEW_BOOKMARKS = "bookmarks"
const val SCREEN_VIEW_BOOKMARK_SHORTCUT = "bookmark_shortcut"
const val SCREEN_VIEW_CALENDAR_EVENT = "calendar_event"
const val SCREEN_VIEW_CALENDAR_TODO = "calendar_todo"
const val SCREEN_VIEW_CALENDAR = "calendar"
const val SCREEN_VIEW_CANVAS_CONTEXT_LIST = "canvas_context_list"
const val SCREEN_VIEW_COLOR_PICKER = "color_picker"
const val SCREEN_VIEW_COMMENT_LIBRARY = "comment_library"
const val SCREEN_VIEW_CONFERENCE_DETAILS = "conference_details"
const val SCREEN_VIEW_CONFERENCE_LIST = "conference_list"
const val SCREEN_VIEW_CONFIRM_DELETE_FILE_FOLDER = "confirm_delete_file_folder"
const val SCREEN_VIEW_CONFIRM_REMOVE_ASSIGNMENT_OVERRIDE = "confirm_remove_assignment_override"
const val SCREEN_VIEW_COURSE_BROWSER = "course_browser"
const val SCREEN_VIEW_COURSE_BROWSER_EMPTY = "course_browser_empty"
const val SCREEN_VIEW_COURSE_MODULE_PROGRESSION = "course_module_progression"
const val SCREEN_VIEW_COURSE_SETTINGS = "course_settings"
const val SCREEN_VIEW_CREATE_ANNOUNCEMENT = "create_announcement"
const val SCREEN_VIEW_CREATE_DISCUSSION = "create_discussion"
const val SCREEN_VIEW_CREATE_DISCUSSION_REDESIGN = "create_discussion_redesign"
const val SCREEN_VIEW_CREATE_FOLDER = "create_folder"
const val SCREEN_VIEW_CREATE_OR_EDIT_ANNOUNCEMENT = "create_or_edit_announcement"
const val SCREEN_VIEW_CREATE_OR_EDIT_PAGE_DETAILS = "create_or_edit_page_details"
const val SCREEN_VIEW_CRITERION_LONG_DESCRIPTION = "criterion_long_description"
const val SCREEN_VIEW_CUSTOMIZE_GRADE = "customize_grade"
const val SCREEN_VIEW_CUSTOM_RUBRIC_RATING = "custom_rubric_rating"
const val SCREEN_VIEW_DASHBOARD = "dashboard"
const val SCREEN_VIEW_DASHBOARD_NOTIFICATIONS = "dashboard_notifications"
const val SCREEN_VIEW_DATE_PICKER = "date_picker"
const val SCREEN_VIEW_DISCUSSION_DETAILS = "discussion_details"
const val SCREEN_VIEW_DISCUSSION_DETAILS_REDESIGN = "discussion_details_redesign"
const val SCREEN_VIEW_DISCUSSION_LIST = "discussion_list"
const val SCREEN_VIEW_DISCUSSION_MOVE_TO = "discussion_move_to"
const val SCREEN_VIEW_DISCUSSIONS_REPLY = "discussions_reply"
const val SCREEN_VIEW_DISCUSSIONS_UPDATE = "discussions_update"
const val SCREEN_VIEW_DUE_DATES = "due_dates"
const val SCREEN_VIEW_EDIT_ASSIGNMENT_DETAILS = "edit_assignment_details"
const val SCREEN_VIEW_EDIT_COURSE_NAME = "edit_course_name"
const val SCREEN_VIEW_EDIT_COURSE_NICKNAME = "edit_course_nickname"
const val SCREEN_VIEW_EDIT_DASHBOARD = "edit_dashboard"
const val SCREEN_VIEW_EDIT_FAVORITES = "edit_favorites"
const val SCREEN_VIEW_EDIT_FILE_FOLDER = "edit_file_folder"
const val SCREEN_VIEW_EDIT_PAGE_DETAILS = "edit_page_details"
const val SCREEN_VIEW_EDIT_RUBRIC_COMMENT = "edit_rubric_comment"
const val SCREEN_VIEW_EDIT_QUIZ_DETAILS = "edit_quiz_details"
const val SCREEN_VIEW_EDIT_SYLLABUS = "edit_syllabus"
const val SCREEN_VIEW_ELEMENTARY_COURSE = "elementary_course"
const val SCREEN_VIEW_ELEMENTARY_DASHBOARD = "elementary_dashboard"
const val SCREEN_VIEW_FATAL_ERROR = "fatal_error"
const val SCREEN_VIEW_FEEDBACK = "feedback"
const val SCREEN_VIEW_FIND_SCHOOL = "find_school"
const val SCREEN_VIEW_FILE_DETAILS = "file_details"
const val SCREEN_VIEW_FILE_LIST = "file_list"
const val SCREEN_VIEW_FILE_SEARCH = "file_search"
const val SCREEN_VIEW_GRADES_LIST = "grades_list"
const val SCREEN_VIEW_HELP = "help"
const val SCREEN_VIEW_INBOX_COMPOSE = "inbox_compose"
const val SCREEN_VIEW_INBOX_CONVERSATION = "inbox_conversation"
const val SCREEN_VIEW_INBOX = "inbox"
const val SCREEN_VIEW_INBOX_RECIPIENTS = "inbox_recipients"
const val SCREEN_VIEW_K5_GRADES = "k5_grades"
const val SCREEN_VIEW_K5_HOMEROOM = "k5_homeroom"
const val SCREEN_VIEW_K5_IMPORTANT_DATES = "k5_important_dates"
const val SCREEN_VIEW_K5_RESOURCES = "k5_resources"
const val SCREEN_VIEW_K5_SCHEDULE = "k5_schedule"
const val SCREEN_VIEW_LEGAL = "legal"
const val SCREEN_VIEW_LOGIN = "login"
const val SCREEN_VIEW_LOGIN_LANDING = "login_landing"
const val SCREEN_VIEW_LOGIN_WITH_QR = "login_with_qr"
const val SCREEN_VIEW_LTI_LAUNCH = "lti_launch"
const val SCREEN_VIEW_LOCKED_MODULE_ITEM = "locked_module_item"
const val SCREEN_VIEW_MASTERY_PATH_OPTIONS = "mastery_path_options"
const val SCREEN_VIEW_MASTERY_PATH_SELECTION = "mastery_path_selection"
const val SCREEN_VIEW_MESSAGE_THREAD = "message_thread"
const val SCREEN_VIEW_MOBILE_DATA_WARNING = "mobile_data_warning"
const val SCREEN_VIEW_MODULE_LIST = "module_list"
const val SCREEN_VIEW_MODULE_QUIZ_DECIDER = "module_quiz_decider"
const val SCREEN_VIEW_NO_INTERNET_CONNECTION = "no_internet_connection"
const val SCREEN_VIEW_NOT_A_TEACHER = "not_a_teacher"
const val SCREEN_VIEW_NOTHING_TO_SEE_HERE = "nothing_to_see_here"
const val SCREEN_VIEW_NOTIFICATION_LIST = "notification_list"
const val SCREEN_VIEW_NOTIFICATION_PREFERENCES = "notification_preferences"
const val SCREEN_VIEW_PAGE_DETAILS = "page_details"
const val SCREEN_VIEW_PAGE_LIST = "page_list"
const val SCREEN_VIEW_PAIR_OBSERVER = "pair_observer"
const val SCREEN_VIEW_PANDA_AVATAR = "panda_avatar"
const val SCREEN_VIEW_PASS_FAIL_GRADE = "pass_fail_grade"
const val SCREEN_VIEW_PEOPLE_DETAILS = "people_details"
const val SCREEN_VIEW_PEOPLE_LIST = "people_list"
const val SCREEN_VIEW_POST_GRADE_POLICY = "post_grade_policy"
const val SCREEN_VIEW_PROFILE = "profile"
const val SCREEN_VIEW_PROFILE_EDIT = "profile_edit"
const val SCREEN_VIEW_PROFILE_SETTINGS = "profile_settings"
const val SCREEN_VIEW_PSPDFKIT = "pspdfkit"
const val SCREEN_VIEW_QUIZ_LIST = "quiz_list"
const val SCREEN_VIEW_QUIZ_PREVIEW = "quiz_preview"
const val SCREEN_VIEW_QUIZ_SUBMISSION_VIEW = "quiz_submission_view"
const val SCREEN_VIEW_RATING = "rating"
const val SCREEN_VIEW_SETTINGS = "settings"
const val SCREEN_VIEW_SIGN_IN = "sign_in"
const val SCREEN_VIEW_SMART_SEARCH = "smart_search"
const val SCREEN_VIEW_SPEED_GRADER = "speed_grader"
const val SCREEN_VIEW_SPEED_GRADER_COMMENTS = "speed_grader_comments"
const val SCREEN_VIEW_SPEED_GRADER_EMPTY = "speed_grader_empty"
const val SCREEN_VIEW_SPEED_GRADER_FILES = "speed_grader_files"
const val SCREEN_VIEW_SPEED_GRADER_GRADE = "speed_grader_grade"
const val SCREEN_VIEW_SPEED_GRADER_LTI_SUBMISSION = "speed_grader_lti_submission"
const val SCREEN_VIEW_SPEED_GRADER_QUIZ_SUBMISSION = "speed_grader_quiz_submission"
const val SCREEN_VIEW_SPEED_GRADER_QUIZ_WEB_VIEW = "speed_grader_quiz_web_view"
const val SCREEN_VIEW_SPEED_GRADER_TEXT_SUBMISSION = "speed_grader_text_submission"
const val SCREEN_VIEW_SPEED_GRADER_URL_SUBMISSION = "speed_grader_url_submission"
const val SCREEN_VIEW_STUDENT_VIEW = "student_view"
const val SCREEN_VIEW_STUDIO_WEB_VIEW = "studio_web_view"
const val SCREEN_VIEW_SUBMISSION_COMMENTS = "submission_comments"
const val SCREEN_VIEW_SUBMISSION_DETAILS_EMPTY_CONTENT = "submission_details_empty_content"
const val SCREEN_VIEW_SUBMISSION_DETAILS = "submission_details"
const val SCREEN_VIEW_SUBMISSION_FILES = "submission_files"
const val SCREEN_VIEW_SUBMISSION_RUBRIC = "submission_rubric"
const val SCREEN_VIEW_SUBMISSION_UPLOAD_PICKER = "submission_upload_picker"
const val SCREEN_VIEW_SYLLABUS = "syllabus"
const val SCREEN_VIEW_TEXT_SUBMISSION_UPLOAD = "text_submission_upload"
const val SCREEN_VIEW_TIME_PICKER = "time_picker"
const val SCREEN_VIEW_TO_DO = "to_do"
const val SCREEN_VIEW_TO_DO_LIST = "to_do_list"
const val SCREEN_VIEW_UNKNOWN_ITEM = "unknown_item"
const val SCREEN_VIEW_UPLOAD_FILES = "upload_files"
const val SCREEN_VIEW_UNSAVED_CHANGES_CONTINUE = "unsaved_changes_continue"
const val SCREEN_VIEW_UNSAVED_CHANGES_EXIT = "unsaved_changes_exit"
const val SCREEN_VIEW_UNSUPPORTED_FEATURE = "unsupported_feature"
const val SCREEN_VIEW_UNSUPPORTED_TAB = "unsupported_tab"
const val SCREEN_VIEW_UPLOAD_STATUS_SUBMISSION = "upload_status_submission"
const val SCREEN_VIEW_URL_SUBMISSION_UPLOAD = "url_submission_upload"
const val SCREEN_VIEW_VIDEO_VIEW = "video_view"
const val SCREEN_VIEW_VIEW_HTML = "view_html"
const val SCREEN_VIEW_VIEW_IMAGE = "view_image"
const val SCREEN_VIEW_VIEW_MEDIA = "view_media"
const val SCREEN_VIEW_VIEW_PDF = "view_pdf"
const val SCREEN_VIEW_VIEW_UNSUPPORTED_FILE = "view_unsupported_file"
const val SCREEN_VIEW_WHAT_IF = "what_if"
const val SCREEN_VIEW_QR_PAIRING = "qr_pairing"
const val SCREEN_VIEW_PAIRING_CODE = "pairing_code"
const val SCREEN_VIEW_ANNOUNCEMENT_DETAILS = "announcement_details"
const val SCREEN_VIEW_ALERTS = "alerts"
const val SCREEN_VIEW_ALERT_SETTINGS = "alert_settings"
const val SCREEN_VIEW_COURSES = "courses"
const val SCREEN_VIEW_COURSE_DETAILS = "course_details"
const val SCREEN_VIEW_MANAGE_STUDENTS = "manage_students"
const val SCREEN_VIEW_NOT_A_PARENT = "not_a_parent"
const val SCREEN_VIEW_SIMPLE_WEB_VIEW = "simple_web_view"
