/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.instructure.instui.token.semantic.InstUILayoutSizes
import com.instructure.instui.token.semantic.InstUILayoutTypography
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI RadioInput component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIRadioInput {
    val backgroundColor @Composable get() = InstUISemanticColors.Background.Interactive.Input.base()
    val backgroundHoverColor @Composable get() = InstUISemanticColors.Background.Interactive.Input.hover()
    val backgroundReadonlyColor @Composable get() = InstUISemanticColors.Background.Interactive.Input.readonly()
    val backgroundDisabledColor @Composable get() = InstUISemanticColors.Background.Interactive.Input.disabled()
    val borderColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Input.base()
    val borderHoverColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Input.hover()
    val borderReadonlyColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Input.readonly()
    val borderDisabledColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Input.disabled()
    val borderSelectedColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Input.selected()
    val fontSizeSm = 14.sp
    val fontSizeMd = 16.sp
    val fontSizeLg = 20.sp
    val toggleSmallFontSize = 12.sp
    val toggleMediumFontSize = 14.sp
    val toggleLargeFontSize = 16.sp
    val lineHeightSm = InstUILayoutTypography.LineHeight.Paragraph.textSm
    val lineHeightMd = InstUILayoutTypography.LineHeight.Paragraph.textBase
    val lineHeightLg = InstUILayoutTypography.LineHeight.Paragraph.textBase
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
    val fontWeight = InstUILayoutTypography.FontWeight.Body.base
    val gap = InstUILayoutSizes.Spacing.SpaceSm.spaceSm
    val borderWidth = InstUILayoutSizes.BorderWidth.Interactive.base
    val labelBaseColor @Composable get() = InstUISemanticColors.Text.base()
    val labelHoverColor @Composable get() = InstUISemanticColors.Text.base()
    val labelDisabledColor @Composable get() = InstUISemanticColors.Text.Interactive.Disabled.base()
    val labelReadonlyColor @Composable get() = InstUISemanticColors.Text.base()
    val controlSizeSm = InstUILayoutSizes.Size.ChoiceControl.height_sm
    val controlSizeMd = InstUILayoutSizes.Size.ChoiceControl.height_md
    val controlSizeLg = InstUILayoutSizes.Size.ChoiceControl.height_lg
    val checkedInsetSm = 6.dp
    val checkedInsetMd = 6.dp
    val checkedInsetLg = 6.dp
    val toggleSmallHeight = InstUILayoutSizes.Size.Interactive.height_sm
    val toggleMediumHeight = InstUILayoutSizes.Size.Interactive.height_md
    val toggleLargeHeight = InstUILayoutSizes.Size.Interactive.height_lg
    val controlVerticalMargin = 0.dp
    val toggleBackgroundDanger @Composable get() = InstUISemanticColors.Background.warning()
    val toggleBackgroundOff @Composable get() = InstUISemanticColors.Background.success()
    val toggleBackgroundSuccess @Composable get() = InstUISemanticColors.Background.success()
    val toggleBackgroundWarning @Composable get() = InstUISemanticColors.Background.warning()
    val toggleHandleText @Composable get() = InstUISemanticColors.Text.onColor()
    val toggleBorderRadius = InstUILayoutSizes.BorderRadius.Sm.sm
    val toggleBorderWidth = InstUILayoutSizes.BorderWidth.Lg.lg
    /**
     * Box shadow (not directly representable in Compose).
     *   Shadow 1: x={dropShadow.x.elevation1.dropshadow1}, y={dropShadow.y.elevation1.dropshadow1}, blur={dropShadow.blur.elevation1.dropshadow1}, spread={dropShadow.spread.elevation1.dropshadow1}, color={color.dropShadow.shadowColor1}, type=dropShadow
     *   Shadow 2: x={dropShadow.x.elevation1.dropshadow2}, y={dropShadow.y.elevation1.dropshadow2}, blur={dropShadow.blur.elevation1.dropshadow2}, spread={dropShadow.spread.elevation1.dropshadow2}, color={color.dropShadow.shadowColor2}, type=innerShadow
     */
    // val toggleShadow: BoxShadow — not supported in Compose
}
