/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import com.instructure.instui.BorderStyle
import com.instructure.instui.token.semantic.InstUILayoutSizes
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI FileDrop component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIFileDrop {
    val acceptedColor @Composable get() = InstUISemanticColors.Stroke.brand()
    val backgroundColor @Composable get() = InstUISemanticColors.Background.container()
    val borderColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Input.base()
    val borderRadius = InstUILayoutSizes.BorderRadius.Container.md
    val borderStyle = BorderStyle.Dashed
    val borderWidth = InstUILayoutSizes.BorderWidth.Sm.sm
    val hoverBorderColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Input.hover()
    val rejectedColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Action.Destructive.Secondary.base()
}
