/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI Spinner component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUISpinner {
    val color @Composable get() = InstUISemanticColors.Icon.info()
    val inverseColor @Composable get() = InstUISemanticColors.Icon.onColor()
    val trackColor @Composable get() = InstUISemanticColors.Background.opacity()
    val strokeWidthXs = 4.dp
    val strokeWidthSm = 6.dp
    val strokeWidthMd = 8.dp
    val strokeWidthLg = 12.dp
    val containerSizeXs = 24.dp
    val containerSizeSm = 48.dp
    val containerSizeMd = 80.dp
    val containerSizeLg = 112.dp
    val spinnerSizeXs = 16.dp
    val spinnerSizeSm = 32.dp
    val spinnerSizeMd = 56.dp
    val spinnerSizeLg = 72.dp
}
