/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.primitives.InstUIColors
import com.instructure.instui.token.semantic.InstUILayoutTypography
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI ProgressCircle component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIProgressCircle {
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
    val fontWeight = InstUILayoutTypography.FontWeight.Heading.base
    val lineHeight = InstUILayoutTypography.LineHeight.Heading.base
    val xSmallSize = 48.dp
    val xSmallCircumference = 100.dp
    val xSmallTransform = 24.dp
    val xSmallStrokeWidth = 3.2.dp
    val smallSize = 80.dp
    val smallCircumference = 176.dp
    val smallTransform = 40.dp
    val smallStrokeWidth = 8.dp
    val mediumSize = 112.dp
    val mediumCircumference = 276.dp
    val mediumTransform = 56.dp
    val mediumStrokeWidth = 10.dp
    val largeSize = 144.dp
    val largeCircumference = 352.dp
    val largeTransform = 72.dp
    val largeStrokeWidth = 14.dp
    val color @Composable get() = InstUISemanticColors.Text.base()
    val colorInverse @Composable get() = InstUISemanticColors.Text.inverse()
    val trackColor @Composable get() = InstUISemanticColors.Background.base()
    val trackColorInverse = InstUIColors.transparent
    val trackBorderColor @Composable get() = InstUISemanticColors.Stroke.base()
    val trackBorderColorInverse @Composable get() = InstUISemanticColors.Stroke.inverse()
    val meterColorAlert @Composable get() = InstUISemanticColors.Stroke.info()
    val meterColorAlertInverse @Composable get() = InstUISemanticColors.Stroke.inverse()
    val meterColorBrand @Composable get() = InstUISemanticColors.Stroke.brand()
    val meterColorBrandInverse @Composable get() = InstUISemanticColors.Stroke.inverse()
    val meterColorDanger @Composable get() = InstUISemanticColors.Stroke.error()
    val meterColorDangerInverse @Composable get() = InstUISemanticColors.Stroke.inverse()
    val meterColorInfo @Composable get() = InstUISemanticColors.Stroke.info()
    val meterColorInfoInverse @Composable get() = InstUISemanticColors.Stroke.inverse()
    val meterColorSuccess @Composable get() = InstUISemanticColors.Stroke.success()
    val meterColorSuccessInverse @Composable get() = InstUISemanticColors.Stroke.inverse()
    val meterColorWarning @Composable get() = InstUISemanticColors.Stroke.warning()
    val meterColorWarningInverse @Composable get() = InstUISemanticColors.Stroke.inverse()
    val xSmallRadius = 16.dp
    val smallRadius = 28.8.dp
    val mediumRadius = 44.dp
    val largeRadius = 56.dp
    val xSmallBorderOffset = 15.04.dp
    val smallBorderOffset = 25.8.dp
    val  mediumBorderOffset = 40.dp
    val largeBorderOffset = 50.dp
}
