/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.instructure.instui.BorderStyle
import com.instructure.instui.token.primitives.InstUIColors
import com.instructure.instui.token.semantic.InstUILayoutSizes
import com.instructure.instui.token.semantic.InstUILayoutTypography
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI Tabs component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUITabs {
    object Tabs {
        val defaultBackground = InstUIColors.transparent
        val scrollFadeColor @Composable get() = InstUISemanticColors.Background.base()
        val scrollOverlayWidthDefault = 80.dp
        val scrollOverlayWidthSecondary = 48.dp
        val tabVerticalOffset = 1.dp
        val zIndex = "1"
    }

    object TabsPanel {
        val background = InstUIColors.transparent
        val borderColor @Composable get() = InstUISemanticColors.Stroke.base()
        val textColor @Composable get() = InstUISemanticColors.Text.base()
        val borderWidth = InstUILayoutSizes.BorderWidth.Sm.sm
        val defaultOverflowY = "auto"
        val fontFamily = InstUILayoutTypography.FontFamily.Base.base
        val fontSize = 16.sp
        val fontWeight = InstUILayoutTypography.FontWeight.Body.base
        val lineHeight = InstUILayoutTypography.LineHeight.Paragraph.base
    }

    object TabsTab {
        val defaultTextColor @Composable get() = InstUISemanticColors.Text.base()
        val defaultHoverBorderColor @Composable get() = InstUISemanticColors.Stroke.base()
        val defaultSelectedBorderColor @Composable get() = InstUISemanticColors.Stroke.brand()
        val fontFamily = InstUILayoutTypography.FontFamily.Base.base
        val fontSize = 16.sp
        val fontWeight = InstUILayoutTypography.FontWeight.Body.base
        val lineHeight = InstUILayoutTypography.LineHeight.Standalone.base
        val secondaryTextColor @Composable get() = InstUISemanticColors.Text.base()
        val secondarySelectedTextColor @Composable get() = InstUISemanticColors.Text.inverse()
        val secondarySelectedBackground @Composable get() = InstUISemanticColors.Background.brand()
        val secondarySelectedBorderColor @Composable get() = InstUISemanticColors.Stroke.brand()
        val zIndex = "1"
    }
}
