/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import com.instructure.instui.token.semantic.InstUILayoutTypography
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI Text component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIText {
    /** Used for introductory or overview text that explains the purpose or context of an entire page. */
    val descriptionPage = TextStyle(
        fontFamily = InstUILayoutTypography.FontFamily.Base.base,
        fontWeight = InstUILayoutTypography.FontWeight.Body.base,
        fontSize = 20.sp,
        lineHeight = 1.5.em,
    )
    /** Used for text that introduces or summarizes a specific section within a page. */
    val descriptionSection = TextStyle(
        fontFamily = InstUILayoutTypography.FontFamily.Base.base,
        fontWeight = InstUILayoutTypography.FontWeight.Body.base,
        fontSize = 16.sp,
        lineHeight = 1.5.em,
    )
    /** Used for standard descriptive body text that provides detailed information. */
    val content = TextStyle(
        fontFamily = InstUILayoutTypography.FontFamily.Base.base,
        fontWeight = InstUILayoutTypography.FontWeight.Body.base,
        fontSize = 16.sp,
        lineHeight = 1.5.em,
    )
    /** Used to highlight key statements or essential information within descriptive text. */
    val contentImportant = TextStyle(
        fontFamily = InstUILayoutTypography.FontFamily.Base.base,
        fontWeight = InstUILayoutTypography.FontWeight.Body.strong,
        fontSize = 16.sp,
        lineHeight = 1.5.em,
    )
    /** Used to style quoted or referenced text distinct from the main content. */
    val contentQuote = TextStyle(
        fontFamily = InstUILayoutTypography.FontFamily.Base.base,
        // fontWeight: "Medium Italic" — not directly mappable,
        fontSize = 16.sp,
        lineHeight = 1.5.em,
    )
    /** Used for fine-print or secondary descriptions such as notes or disclaimers. */
    val contentSmall = TextStyle(
        fontFamily = InstUILayoutTypography.FontFamily.Base.base,
        fontWeight = InstUILayoutTypography.FontWeight.Body.base,
        fontSize = 14.sp,
        lineHeight = 1.5.em,
    )
    /** Used for short explanatory text accompanying data visualizations, icons, or UI elements. */
    val legend = TextStyle(
        fontFamily = InstUILayoutTypography.FontFamily.Base.base,
        fontWeight = InstUILayoutTypography.FontWeight.Body.base,
        fontSize = 12.sp,
        lineHeight = 1.5.em,
    )
    val fontSizeXSmall = 12.sp
    val fontSizeSmall = 14.sp
    val fontSizeMedium = 16.sp
    val fontSizeLarge = 28.sp
    val fontSizeXLarge = 40.sp
    val fontSizeXXLarge = 38.sp
    val fontWeightLight = FontWeight(300)
    val fontWeightNormal = InstUILayoutTypography.FontWeight.Body.base
    val fontWeightBold = InstUILayoutTypography.FontWeight.Body.strong
    val fontWeightImportant = InstUILayoutTypography.FontWeight.Body.strong
    val fontWeightRegular = InstUILayoutTypography.FontWeight.Body.base
    val lineHeight = 1.5f
    val lineHeight100 = 1f
    val lineHeight125 = 1.25f
    val lineHeight150 = 1.5f
    val lineHeightCondensed = 1.25f
    val lineHeightDouble = 2f
    val lineHeightFit = 1.125f
    val paragraphMargin = /* "1.5rem 0rem" — not directly usable in Compose */ 0.dp
    val letterSpacingCondensed = (-1).sp
    val letterSpacingExpanded = 1.sp
    val letterSpacingNormal = 0.sp
    val aiBackgroundColor @Composable get() = InstUISemanticColors.Background.aiText()
    val aiColor @Composable get() = InstUISemanticColors.Text.aiColor()
    val primaryColor @Composable get() = InstUISemanticColors.Text.Interactive.Navigation.Primary.base()
    val errorColor @Composable get() = InstUISemanticColors.Text.error()
    val baseColor @Composable get() = InstUISemanticColors.Text.base()
    val baseOnColor @Composable get() = InstUISemanticColors.Text.onColor()
    val inverseColor @Composable get() = InstUISemanticColors.Text.inverse()
    val mutedColor @Composable get() = InstUISemanticColors.Text.muted()
    val mutedOnColor @Composable get() = InstUISemanticColors.Text.onColor()
    val successColor @Composable get() = InstUISemanticColors.Text.success()
    val warningColor @Composable get() = InstUISemanticColors.Text.warning()
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
    val fontFamilyMonospace = InstUILayoutTypography.FontFamily.Code.code
}
