/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.unit.sp
import com.instructure.instui.token.semantic.InstUILayoutSizes
import com.instructure.instui.token.semantic.InstUILayoutTypography
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI Link component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUILink {
    val textColor @Composable get() = InstUISemanticColors.Text.Interactive.Navigation.Primary.base()
    val textHoverColor @Composable get() = InstUISemanticColors.Text.Interactive.Navigation.Primary.hover()
    val textDisabledColor @Composable get() = InstUISemanticColors.Text.Interactive.Disabled.base()
    val onColorTextColor @Composable get() = InstUISemanticColors.Text.Interactive.Navigation.PrimaryOnColor.base()
    val onColorTextHoverColor @Composable get() = InstUISemanticColors.Text.Interactive.Navigation.PrimaryOnColor.hover()
    val onColorTextDisabledColor @Composable get() = InstUISemanticColors.Text.Interactive.Disabled.onColor()
    val fontSizeSm = 14.sp
    val fontSizeMd = 16.sp
    val fontSizeLg = 28.sp
    val fontWeight = InstUILayoutTypography.FontWeight.Interactive.interactive
    val gapSm = InstUILayoutSizes.Spacing.Space2xs.space2xs
    val gapMd = InstUILayoutSizes.Spacing.SpaceXs.spaceXs
    val gapLg = InstUILayoutSizes.Spacing.SpaceXs.spaceXs
    val lineHeightSm = InstUILayoutTypography.LineHeight.Standalone.textSm
    val lineHeightMd = InstUILayoutTypography.LineHeight.Standalone.textBase
    val lineHeightLg = InstUILayoutTypography.LineHeight.Standalone.textXl
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
    val textDecorationWithinText = "underline"
    val textDecorationOutsideText = "none"
    val unstyledTextColor @Composable get() = InstUISemanticColors.Text.base()

    object InlineLink {
        val small = TextStyle(
            fontFamily = InstUILayoutTypography.FontFamily.Base.base,
            fontWeight = InstUILayoutTypography.FontWeight.Body.strong,
            fontSize = 14.sp,
            lineHeight = 14.sp,
        )
        val medium = TextStyle(
            fontFamily = InstUILayoutTypography.FontFamily.Base.base,
            fontWeight = InstUILayoutTypography.FontWeight.Body.strong,
            fontSize = 16.sp,
            lineHeight = 24.sp,
        )
        val large = TextStyle(
            fontFamily = InstUILayoutTypography.FontFamily.Base.base,
            fontWeight = InstUILayoutTypography.FontWeight.Body.strong,
            fontSize = 28.sp,
            lineHeight = 24.sp,
        )
    }
}
