/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI Icon component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIIcon {
    val sizeXs = 12.dp
    val sizeSm = 16.dp
    val sizeMd = 20.dp
    val sizeLg = 24.dp
    val sizeXl = 32.dp
    val size2xl = 36.dp
    val illuSm = 48.dp
    val illuMd = 80.dp
    val illuLg = 160.dp
    val strokeWidthXs = 1.dp
    val strokeWidthSm = 1.25.dp
    val strokeWidthMd = 1.5.dp
    val strokeWidthLg = 2.dp
    val strokeWidthXl = 2.5.dp
    val strokeWidth2xl = 3.dp
    val strokeWidthIlluSm = 4.dp
    val strokeWidthIlluMd = 8.dp
    val strokeWidthIlluLg = 12.dp
    val baseColor @Composable get() = InstUISemanticColors.Icon.base()
    val mutedColor @Composable get() = InstUISemanticColors.Icon.muted()
    val successColor @Composable get() = InstUISemanticColors.Icon.success()
    val errorColor @Composable get() = InstUISemanticColors.Icon.error()
    val warningColor @Composable get() = InstUISemanticColors.Icon.warning()
    val infoColor @Composable get() = InstUISemanticColors.Icon.info()
    val onColor @Composable get() = InstUISemanticColors.Icon.onColor()
    val inverseColor @Composable get() = InstUISemanticColors.Icon.inverse()
    val disabledBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Disabled.base()
    val disabledOnColor @Composable get() = InstUISemanticColors.Icon.Interactive.Disabled.onColor()
    val dark @Composable get() = InstUISemanticColors.Icon.dark()
    val sideNavColor @Composable get() = InstUISemanticColors.Icon.brand()
    val sideNavActiveColor @Composable get() = InstUISemanticColors.Icon.inverse()
    val navigationPrimaryBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Navigation.Primary.base()
    val navigationPrimaryHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Navigation.Primary.hover()
    val navigationPrimaryActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Navigation.Primary.active()
    val navigationPrimaryOnColorBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Navigation.PrimaryOnColor.base()
    val navigationPrimaryOnColorHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Navigation.PrimaryOnColor.hover()
    val navigationPrimaryOnColorActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Navigation.PrimaryOnColor.active()
    val actionSecondaryBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Secondary.base()
    val actionSecondaryHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Secondary.hover()
    val actionSecondaryActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Secondary.active()
    val actionSecondaryDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Secondary.disabled()
    val actionStatusBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Status.base()
    val actionStatusHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Status.hover()
    val actionStatusActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Status.active()
    val actionStatusDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Status.disabled()
    val actionAiSecondaryTopGradientBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.AiSecondary.TopGradient.base()
    val actionAiSecondaryBottomGradientBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.AiSecondary.BottomGradient.base()
    val actionAiBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Ai.base()
    val actionAiHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Ai.hover()
    val actionAiActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Ai.active()
    val actionAiDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Ai.disabled()
    val actionPrimaryBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Primary.base()
    val actionPrimaryHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Primary.hover()
    val actionPrimaryActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Primary.active()
    val actionPrimaryDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Primary.disabled()
    val actionPrimaryOnColorBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.PrimaryOnColor.base()
    val actionTertiaryBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Tertiary.base()
    val actionTertiaryHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Tertiary.hover()
    val actionTertiaryActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Tertiary.active()
    val actionPrimaryOnColorHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.PrimaryOnColor.hover()
    val actionPrimaryOnColorActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.PrimaryOnColor.active()
    val actionPrimaryOnColorDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.PrimaryOnColor.disabled()
    val actionTertiaryDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.Tertiary.disabled()
    val actionSuccessSecondaryBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.SuccessSecondary.base()
    val actionSuccessSecondaryHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.SuccessSecondary.hover()
    val actionSuccessSecondaryActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.SuccessSecondary.active()
    val actionSuccessSecondaryDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.SuccessSecondary.disabled()
    val actionDestructiveSecondaryBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.DestructiveSecondary.base()
    val actionDestructiveSecondaryHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.DestructiveSecondary.hover()
    val actionDestructiveSecondaryActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.DestructiveSecondary.active()
    val actionDestructiveSecondaryDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.DestructiveSecondary.disabled()
    val accentBlueColor @Composable get() = InstUISemanticColors.Icon.Accent.blue()
    val accentGreenColor @Composable get() = InstUISemanticColors.Icon.Accent.green()
    val accentRedColor @Composable get() = InstUISemanticColors.Icon.Accent.red()
    val accentOrangeColor @Composable get() = InstUISemanticColors.Icon.Accent.orange()
    val accentGreyColor @Composable get() = InstUISemanticColors.Icon.Accent.grey()
    val accentAshColor @Composable get() = InstUISemanticColors.Icon.Accent.ash()
    val accentPlumColor @Composable get() = InstUISemanticColors.Icon.Accent.plum()
    val accentVioletColor @Composable get() = InstUISemanticColors.Icon.Accent.violet()
    val accentStoneColor @Composable get() = InstUISemanticColors.Icon.Accent.stone()
    val accentSkyColor @Composable get() = InstUISemanticColors.Icon.Accent.sky()
    val accentHoneyColor @Composable get() = InstUISemanticColors.Icon.Accent.honey()
    val accentSeaColor @Composable get() = InstUISemanticColors.Icon.Accent.sea()
    val accentAuroraColor @Composable get() = InstUISemanticColors.Icon.Accent.aurora()
    val actionAiSecondaryDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.AiSecondary.disabled()
    val actionSecondaryOnColorBaseColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.SecondaryOnColor.base()
    val actionSecondaryOnColorHoverColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.SecondaryOnColor.hover()
    val actionSecondaryOnColorActiveColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.SecondaryOnColor.active()
    val actionSecondaryOnColorDisabledColor @Composable get() = InstUISemanticColors.Icon.Interactive.Action.SecondaryOnColor.disabled()
}
