/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.instructure.instui.token.semantic.InstUILayoutSizes
import com.instructure.instui.token.semantic.InstUILayoutTypography
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI Avatar component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIAvatar {
    val backgroundColor @Composable get() = InstUISemanticColors.Background.base()
    val borderColor @Composable get() = InstUISemanticColors.Stroke.base()
    val borderWidthSm = InstUILayoutSizes.BorderWidth.Sm.sm
    val borderWidthMd = InstUILayoutSizes.BorderWidth.Md.md
    /**
     * Box shadow (not directly representable in Compose).
     *   Shadow 1: x=0, y=0, blur=1rem, spread=0, color=rgba(45,59,69,0.12), type=innerShadow
     */
    // val boxShadow: BoxShadow — not supported in Compose
    val fontWeight = InstUILayoutTypography.FontWeight.Heading.base
    val blueBackgroundColor @Composable get() = InstUISemanticColors.Background.Accent.blue()
    val blueTextColor @Composable get() = InstUISemanticColors.Text.Accent.blue()
    val greenBackgroundColor @Composable get() = InstUISemanticColors.Background.Accent.green()
    val greenTextColor @Composable get() = InstUISemanticColors.Text.Accent.green()
    val redBackgroundColor @Composable get() = InstUISemanticColors.Background.Accent.red()
    val redTextColor @Composable get() = InstUISemanticColors.Text.Accent.red()
    val orangeBackgroundColor @Composable get() = InstUISemanticColors.Background.Accent.orange()
    val orangeTextColor @Composable get() = InstUISemanticColors.Text.Accent.orange()
    val greyBackgroundColor @Composable get() = InstUISemanticColors.Background.Accent.grey()
    val greyTextColor @Composable get() = InstUISemanticColors.Text.Accent.grey()
    val ashBackgroundColor @Composable get() = InstUISemanticColors.Background.Accent.ash()
    val ashTextColor @Composable get() = InstUISemanticColors.Text.Accent.ash()
    val aiBottomGradientColor @Composable get() = InstUISemanticColors.Background.aiBottomGradient()
    val aiTopGradientColor @Composable get() = InstUISemanticColors.Background.aiTopGradient()
    val textOnColor @Composable get() = InstUISemanticColors.Text.onColor()
    val size2xs = 24.dp
    val sizeXs = 32.dp
    val sizeSm = 40.dp
    val sizeMd = 48.dp
    val sizeLg = 56.dp
    val sizeXl = 64.dp
    val size2xl = 80.dp
    val fontSize2xs = 12.sp
    val fontSizeXs = 12.sp
    val fontSizeSm = 14.sp
    val fontSizeMd = 16.sp
    val fontSizeLg = 20.sp
    val fontSizeXl = 28.sp
    val fontSize2xl = 40.sp
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
    val rectangleRadius = InstUILayoutSizes.BorderRadius.Sm.sm
}
