/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.instructure.instui.token.semantic.InstUILayoutSizes
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI ColorPreset component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIColorPreset {
    val popoverContentBlockBottomMargin = InstUILayoutSizes.Spacing.SpaceMd.spaceMd
    val popoverContentBlockTopMargin = InstUILayoutSizes.Spacing.SpaceXl.spaceXl
    val popoverContentBlockTopPadding = InstUILayoutSizes.Spacing.SpaceXl.spaceXl
    val popoverDividerColor @Composable get() = InstUISemanticColors.Stroke.muted()
    val popoverFooterColor @Composable get() = InstUISemanticColors.Background.ElevatedSurface.base()
    val selectedIndicatorBackgroundColor @Composable get() = InstUISemanticColors.Background.onColor()
    val selectedIndicatorBorderColor @Composable get() = InstUISemanticColors.Stroke.Container.dark()
    val smallBorder = InstUILayoutSizes.BorderWidth.Sm.sm
    val smallSpacing = InstUILayoutSizes.Spacing.SpaceMd.spaceMd
    val xxSmallSpacing = 6.dp
}
