/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.instructure.instui.token.primitives.InstUIColors
import com.instructure.instui.token.semantic.InstUILayoutSizes
import com.instructure.instui.token.semantic.InstUILayoutTypography
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI ProgressBar component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUIProgressBar {
    val borderRadius = InstUILayoutSizes.BorderRadius.Md.md
    val fontFamily = InstUILayoutTypography.FontFamily.Base.base
    val fontSize = 16.sp
    val fontWeight = InstUILayoutTypography.FontWeight.Body.base
    val lineHeight = InstUILayoutTypography.LineHeight.Heading.base
    val xSmallHeight = 8.dp
    val smallHeight = 16.dp
    val mediumHeight = 24.dp
    val meterColorAlert @Composable get() = InstUISemanticColors.Background.brand()
    val meterColorAlertInverse @Composable get() = InstUISemanticColors.Background.base()
    val meterColorBrand @Composable get() = InstUISemanticColors.Background.brand()
    val meterColorBrandInverse @Composable get() = InstUISemanticColors.Background.base()
    val meterColorDanger @Composable get() = InstUISemanticColors.Background.brand()
    val meterColorDangerInverse @Composable get() = InstUISemanticColors.Background.base()
    val meterColorInfo @Composable get() = InstUISemanticColors.Background.brand()
    val meterColorInfoInverse @Composable get() = InstUISemanticColors.Background.base()
    val meterColorSuccess @Composable get() = InstUISemanticColors.Background.brand()
    val meterColorSuccessInverse @Composable get() = InstUISemanticColors.Background.base()
    val meterColorWarning @Composable get() = InstUISemanticColors.Background.brand()
    val meterColorWarningInverse @Composable get() = InstUISemanticColors.Background.base()
    val largeHeight = 32.dp
    val trackBottomBorderColor = InstUIColors.transparent
    val trackBottomBorderColorInverse = InstUIColors.transparent
    val trackBottomBorderWidth = InstUILayoutSizes.BorderWidth.Sm.sm
    val trackColor = InstUIColors.transparent
    val trackColorInverse = InstUIColors.transparent
    val valuePadding = InstUILayoutSizes.Spacing.SpaceSm.spaceSm
    val textColor @Composable get() = InstUISemanticColors.Text.muted()
    val textColorInverse @Composable get() = InstUISemanticColors.Text.inverse()
    val xSmallValueFontSize = 16.sp
    val smallValueFontSize = 16.sp
    val mediumValueFontSize = 16.sp
    val largeValueFontSize = 16.sp
    val borderColor @Composable get() = InstUISemanticColors.Stroke.brand()
    val borderColorInverse @Composable get() = InstUISemanticColors.Stroke.inverse()
}
