/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.component

import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.instructure.instui.BorderStyle
import com.instructure.instui.token.semantic.InstUILayoutSizes
import com.instructure.instui.token.semantic.InstUISemanticColors

/**
 * InstUI SharedTokens component tokens.
 *
 * Generated from instructure-ui component token definitions.
 * These tokens reference the semantic layer for theme-aware values.
 */
object InstUISharedTokens {
    object Background {
        val containerColor @Composable get() = InstUISemanticColors.Background.container()
        val baseColor @Composable get() = InstUISemanticColors.Background.base()
        val pageColor @Composable get() = InstUISemanticColors.Background.page()
        val mutedColor @Composable get() = InstUISemanticColors.Background.muted()
        val brandColor @Composable get() = InstUISemanticColors.Background.brand()
        val onColor @Composable get() = InstUISemanticColors.Background.onColor()
        val inverseColor @Composable get() = InstUISemanticColors.Background.inverse()
        val successColor @Composable get() = InstUISemanticColors.Background.success()
        val errorColor @Composable get() = InstUISemanticColors.Background.error()
        val infoColor @Composable get() = InstUISemanticColors.Background.info()
        val warningColor @Composable get() = InstUISemanticColors.Background.warning()
        val aiTopGradientColor @Composable get() = InstUISemanticColors.Background.aiTopGradient()
        val aiBottomGradientColor @Composable get() = InstUISemanticColors.Background.aiBottomGradient()
        val aiTextColor @Composable get() = InstUISemanticColors.Background.aiText()
        val accentAsh @Composable get() = InstUISemanticColors.Background.Accent.ash()
        val accentAurora @Composable get() = InstUISemanticColors.Background.Accent.aurora()
        val accentBlue @Composable get() = InstUISemanticColors.Background.Accent.blue()
        val accentGreen @Composable get() = InstUISemanticColors.Background.Accent.green()
        val accentGrey @Composable get() = InstUISemanticColors.Background.Accent.grey()
        val accentHoney @Composable get() = InstUISemanticColors.Background.Accent.honey()
        val accentOrange @Composable get() = InstUISemanticColors.Background.Accent.orange()
        val accentPlum @Composable get() = InstUISemanticColors.Background.Accent.plum()
        val accentRed @Composable get() = InstUISemanticColors.Background.Accent.red()
        val accentSea @Composable get() = InstUISemanticColors.Background.Accent.sea()
        val accentSky @Composable get() = InstUISemanticColors.Background.Accent.sky()
        val accentStone @Composable get() = InstUISemanticColors.Background.Accent.stone()
        val accentViolet @Composable get() = InstUISemanticColors.Background.Accent.violet()
    }

    object BorderRadius {
        val xs = InstUILayoutSizes.BorderRadius.Xs.xs
        val sm = InstUILayoutSizes.BorderRadius.Sm.sm
        val md = InstUILayoutSizes.BorderRadius.Md.md
        val lg = InstUILayoutSizes.BorderRadius.Lg.lg
        val xl = InstUILayoutSizes.BorderRadius.Xl.xl
        val xxl = InstUILayoutSizes.BorderRadius.Xxl.xxl
        val full = 15984.dp

        object Card {
            val sm = 12.dp
            val md = InstUILayoutSizes.BorderRadius.Container.md
            val lg = InstUILayoutSizes.BorderRadius.Container.lg

            object NestedContainer {
                val sm = InstUILayoutSizes.BorderRadius.Sm.sm
                val md = InstUILayoutSizes.BorderRadius.Sm.sm
                val lg = InstUILayoutSizes.BorderRadius.Md.md
            }
        }
    }

    object BoxShadow {
        /**
         * Box shadow (not directly representable in Compose).
         *   Shadow 1: x={dropShadow.x.elevation1.dropshadow1}, y={dropShadow.y.elevation1.dropshadow1}, blur={dropShadow.blur.elevation1.dropshadow1}, spread={dropShadow.spread.elevation1.dropshadow1}, color={color.dropShadow.shadowColor1}, type=dropShadow
         *   Shadow 2: x={dropShadow.x.elevation1.dropshadow2}, y={dropShadow.y.elevation1.dropshadow2}, blur={dropShadow.blur.elevation1.dropshadow2}, spread={dropShadow.spread.elevation1.dropshadow2}, color={color.dropShadow.shadowColor2}, type=dropShadow
         */
        // val elevation1: BoxShadow — not supported in Compose
        /**
         * Box shadow (not directly representable in Compose).
         *   Shadow 1: x={dropShadow.x.elevation2.dropshadow1}, y={dropShadow.y.elevation2.dropshadow1}, blur={dropShadow.blur.elevation2.dropshadow1}, spread={dropShadow.spread.elevation2.dropshadow1}, color={color.dropShadow.shadowColor2}, type=dropShadow
         *   Shadow 2: x={dropShadow.x.elevation2.dropshadow2}, y={dropShadow.y.elevation2.dropshadow2}, blur={dropShadow.blur.elevation2.dropshadow2}, spread={dropShadow.spread.elevation2.dropshadow2}, color={color.dropShadow.shadowColor1}, type=dropShadow
         */
        // val elevation2: BoxShadow — not supported in Compose
        /**
         * Box shadow (not directly representable in Compose).
         *   Shadow 1: x={dropShadow.x.elevation3.dropshadow1}, y={dropShadow.y.elevation3.dropshadow1}, blur={dropShadow.blur.elevation3.dropshadow1}, spread={dropShadow.spread.elevation3.dropshadow1}, color={color.dropShadow.shadowColor2}, type=dropShadow
         *   Shadow 2: x={dropShadow.x.elevation3.dropshadow2}, y={dropShadow.y.elevation3.dropshadow2}, blur={dropShadow.blur.elevation3.dropshadow2}, spread={dropShadow.spread.elevation3.dropshadow2}, color={color.dropShadow.shadowColor1}, type=dropShadow
         */
        // val elevation3: BoxShadow — not supported in Compose
        /**
         * Box shadow (not directly representable in Compose).
         *   Shadow 1: x={dropShadow.x.elevation4.dropshadow1}, y={dropShadow.y.elevation4.dropshadow1}, blur={dropShadow.blur.elevation4.dropshadow1}, spread={dropShadow.spread.elevation4.dropshadow1}, color={color.dropShadow.shadowColor2}, type=dropShadow
         *   Shadow 2: x={dropShadow.x.elevation4.dropshadow2}, y={dropShadow.y.elevation4.dropshadow2}, blur={dropShadow.blur.elevation4.dropshadow2}, spread={dropShadow.spread.elevation4.dropshadow2}, color={color.dropShadow.shadowColor1}, type=dropShadow
         */
        // val elevation4: BoxShadow — not supported in Compose
    }

    object FocusOutline {
        val offset = InstUILayoutSizes.Spacing.Space2xs.space2xs
        val inset = 0.dp
        val width = InstUILayoutSizes.BorderWidth.Md.md
        val infoColor @Composable get() = InstUISemanticColors.Stroke.Interactive.FocusRing.base()
        val onColor @Composable get() = InstUISemanticColors.Stroke.Interactive.FocusRing.onColor()
        val successColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Action.Success.base()
        val dangerColor @Composable get() = InstUISemanticColors.Stroke.Interactive.Action.Destructive.base()
        val style = BorderStyle.Solid
    }

    object Legacy {
        val radiusSmall = 2.dp
        val radiusMedium = 4.dp
        val radiusLarge = 8.dp

        object Spacing {
            val xxxSmall = 2.dp
            val xxSmall = 6.dp
            val xSmall = 8.dp
            val small = 12.dp
            val mediumSmall = 16.dp
            val medium = 24.dp
            val large = 36.dp
            val xLarge = 48.dp
            val xxLarge = 60.dp
            val space0 = 0.dp
            val space2 = 2.dp
            val space4 = 4.dp
            val space8 = 8.dp
            val space12 = 12.dp
            val space16 = 16.dp
            val space24 = 24.dp
            val space36 = 36.dp
            val space48 = 48.dp
            val space60 = 60.dp
            val sections = 36.dp
            val sectionElements = 24.dp
            val trayElements = 24.dp
            val modalElements = 24.dp
            val moduleElements = 16.dp
            val paddingCardLarge = 24.dp
            val paddingCardMedium = 16.dp
            val paddingCardSmall = 12.dp
            val selects = 16.dp
            val textareas = 16.dp
            val inputFields = 16.dp
            val checkboxes = 16.dp
            val radios = 16.dp
            val toggles = 16.dp
            val buttons = 12.dp
            val tags = 12.dp
            val statusIndicators = 12.dp
            val dataPoints = 12.dp
        }
    }

    object Spacing {
        object Gap {
            val sections = InstUILayoutSizes.Spacing.Gap.sections
            val buttons = InstUILayoutSizes.Spacing.SpaceMd.spaceMd

            object Cards {
                val sm = InstUILayoutSizes.Spacing.Gap.cards_sm
                val md = InstUILayoutSizes.Spacing.Gap.cards_md
                val lg = InstUILayoutSizes.Spacing.Gap.cards_lg

                object NestedContainers {
                    val sm = InstUILayoutSizes.Spacing.SpaceSm.spaceSm
                    val md = InstUILayoutSizes.Spacing.SpaceMd.spaceMd
                    val lg = InstUILayoutSizes.Spacing.SpaceLg.spaceLg
                }
            }

            object Inputs {
                val horizontal = InstUILayoutSizes.Spacing.Gap.inputs_horizontal
                val vertical = InstUILayoutSizes.Spacing.Gap.inputs_vertical
            }
        }

        object General {
            val space2xs = InstUILayoutSizes.Spacing.Space2xs.space2xs
            val spaceXs = InstUILayoutSizes.Spacing.SpaceXs.spaceXs
            val spaceSm = InstUILayoutSizes.Spacing.SpaceSm.spaceSm
            val spaceMd = InstUILayoutSizes.Spacing.SpaceMd.spaceMd
            val spaceLg = InstUILayoutSizes.Spacing.SpaceLg.spaceLg
            val spaceXl = InstUILayoutSizes.Spacing.SpaceXl.spaceXl
            val space2xl = InstUILayoutSizes.Spacing.Space2xl.space2xl
            val spaceNone = 0.dp
        }

        object Padding {
            object Card {
                val sm = InstUILayoutSizes.Spacing.Padding.container_xxs
                val md = InstUILayoutSizes.Spacing.Padding.container_xs
                val lg = InstUILayoutSizes.Spacing.Padding.container_sm
            }
        }
    }

    object Stroke {
        val baseColor @Composable get() = InstUISemanticColors.Stroke.base()
        val mutedColor @Composable get() = InstUISemanticColors.Stroke.muted()
        val strongColor @Composable get() = InstUISemanticColors.Stroke.strong()
        val brandColor @Composable get() = InstUISemanticColors.Stroke.brand()
        val successColor @Composable get() = InstUISemanticColors.Stroke.success()
        val errorColor @Composable get() = InstUISemanticColors.Stroke.error()
        val warningColor @Composable get() = InstUISemanticColors.Stroke.warning()
        val infoColor @Composable get() = InstUISemanticColors.Stroke.info()
        val aiTopGradientColor @Composable get() = InstUISemanticColors.Stroke.aiTopGradient()
        val aiBottomGradientColor @Composable get() = InstUISemanticColors.Stroke.aiBottomGradient()
        val accentAsh @Composable get() = InstUISemanticColors.Stroke.Accent.ash()
        val accentAurora @Composable get() = InstUISemanticColors.Stroke.Accent.aurora()
        val accentBlue @Composable get() = InstUISemanticColors.Stroke.Accent.blue()
        val accentGreen @Composable get() = InstUISemanticColors.Stroke.Accent.green()
        val accentGrey @Composable get() = InstUISemanticColors.Stroke.Accent.grey()
        val accentHoney @Composable get() = InstUISemanticColors.Stroke.Accent.honey()
        val accentOrange @Composable get() = InstUISemanticColors.Stroke.Accent.orange()
        val accentPlum @Composable get() = InstUISemanticColors.Stroke.Accent.plum()
        val accentRed @Composable get() = InstUISemanticColors.Stroke.Accent.red()
        val accentSea @Composable get() = InstUISemanticColors.Stroke.Accent.sea()
        val accentSky @Composable get() = InstUISemanticColors.Stroke.Accent.sky()
        val accentStone @Composable get() = InstUISemanticColors.Background.Accent.stone()
        val accentViolet @Composable get() = InstUISemanticColors.Background.Accent.violet()
        val visualSeparator @Composable get() = InstUISemanticColors.Background.container()
    }

    object StrokeWidth {
        val sm = InstUILayoutSizes.BorderWidth.Sm.sm
        val md = InstUILayoutSizes.BorderWidth.Md.md
        val lg = InstUILayoutSizes.BorderWidth.Lg.lg
    }
}
