/*
 * Copyright (C) 2026 - present Instructure, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// DO NOT EDIT - This file is generated by Style Dictionary
// Run: ./gradlew :libs:instui:generateInstUITokens

package com.instructure.instui.token.semantic

import androidx.compose.ui.unit.sp
import com.instructure.instui.token.primitives.InstUIFontFamilies
import com.instructure.instui.token.primitives.InstUIFontWeights
import com.instructure.instui.token.primitives.InstUISizes

/**
 * InstUI Layout Typography.
 *
 * Font configuration including families, weights, sizes, and line heights.
 */
object InstUILayoutTypography {
    object FontFamily {
        object Base {
            val base = InstUIFontFamilies.atkinson
        }
        object Code {
            val code = InstUIFontFamilies.menlo
        }
        object Heading {
            val heading = InstUIFontFamilies.inclusiveSans
        }
    }

    object FontSize {
        object Text2xl {
            val text2xl = 40.sp
        }
        object TextBase {
            val textBase = 16.sp
        }
        object TextLg {
            val textLg = 20.sp
        }
        object TextSm {
            val textSm = 14.sp
        }
        object TextXl {
            val textXl = 28.sp
        }
        object TextXs {
            val textXs = 12.sp
        }
    }

    object FontWeight {
        object Body {
            val base = InstUIFontWeights.regular
            val strong = InstUIFontWeights.semiBold
        }
        object Heading {
            val base = InstUIFontWeights.semiBold
            val strong = InstUIFontWeights.bold
        }
        object Interactive {
            val interactive = InstUIFontWeights.medium
        }
    }

    object LineHeight {
        object Heading {
            val textLg = InstUISizes.size28
            val textXl = InstUISizes.size32
            val text2xl = InstUISizes.size36
            val text3xl = InstUISizes.size40
            val base = 1.25f
            val loose = 1.5f
        }
        object Label {
            val base = 1.125f
        }
        object Paragraph {
            val textXs = InstUISizes.size20
            val textSm = InstUISizes.size20
            val textBase = InstUISizes.size24
            val base = 1.5f
        }
        object Standalone {
            val textXs = InstUISizes.size12
            val textSm = InstUISizes.size14
            val textBase = InstUISizes.size16
            val textLg = InstUISizes.size20
            val textXl = InstUISizes.size24
            val text2xl = InstUISizes.size28
            val text3xl = InstUISizes.size32
            val text4xl = InstUISizes.size36
            val base = 1.25f
        }
    }
}
